// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: subpkg/subproto.proto

/*
Package subpkg is a generated protocol buffer package.

It is generated from these files:
	subpkg/subproto.proto

It has these top-level messages:
	SubObject
*/
package subpkg

import proto "github.com/vaniila/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/vaniila/protobuf/gogoproto"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type SubObject struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *SubObject) Reset()                    { *m = SubObject{} }
func (m *SubObject) String() string            { return proto.CompactTextString(m) }
func (*SubObject) ProtoMessage()               {}
func (*SubObject) Descriptor() ([]byte, []int) { return fileDescriptorSubproto, []int{0} }

func init() {
	proto.RegisterType((*SubObject)(nil), "subpkg.SubObject")
}

func init() { proto.RegisterFile("subpkg/subproto.proto", fileDescriptorSubproto) }

var fileDescriptorSubproto = []byte{
	// 95 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2d, 0x2e, 0x4d, 0x2a,
	0xc8, 0x4e, 0xd7, 0x07, 0x51, 0x45, 0xf9, 0x25, 0xf9, 0x7a, 0x60, 0x52, 0x88, 0x0d, 0x22, 0x2c,
	0x65, 0x90, 0x9e, 0x59, 0x92, 0x51, 0x9a, 0xa4, 0x97, 0x9c, 0x9f, 0xab, 0x5f, 0x96, 0x98, 0x97,
	0x99, 0x99, 0x93, 0xa8, 0x0f, 0x56, 0x91, 0x54, 0x9a, 0xa6, 0x9f, 0x9e, 0x9f, 0x9e, 0x0f, 0xe6,
	0x80, 0x59, 0x10, 0x9d, 0x4a, 0xdc, 0x5c, 0x9c, 0xc1, 0xa5, 0x49, 0xfe, 0x49, 0x59, 0xa9, 0xc9,
	0x25, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xd4, 0xa6, 0xee, 0x6b, 0x5e, 0x00, 0x00, 0x00,
}
