workspace:
  base: /go
  path: src/github.com/vaniila/protobuf

pipeline:

  build-protobuf:
    image: golang:${GO_VERSION}
    commands:
      # install unzip
      - apt-get update
      - apt-get install --yes unzip
      # download protoc
      - mkdir -p protoc
      - wget https://github.com/google/protobuf/releases/download/v3.2.0/protoc-3.2.0-linux-x86_64.zip -O protoc/protoc.zip
      - unzip protoc/protoc.zip -d protoc/pre
      # install protoc
      - mv protoc/pre/bin/* /usr/local/bin/
      - mv protoc/pre/include/* /usr/local/include/
      # clean up
      - rm -rf protoc
      # build go protobuf
      - go get -v ./...
      - make

  triggle-build-protoc:
    image: plugins/downstream
    repositories:
      - vaniila/protoc@master
    fork: true
    secrets: [ downstream_server, downstream_token ]
    when:
      matrix:
        GO_VERSION: 1.9

matrix:
  GO_VERSION:
    - 1.9
    - 1.8
