workspace:
  base: /go
  path: src/github.com/vaniila/protobuf

pipeline:

  build-protobuf:
    image: alpine:latest
    environment:
      - GOPATH=/go
    commands:
      - export PATH=$GOPATH/bin:$PATH
      - apk --no-cache add --virtual .pb-build ca-certificates make cmake autoconf automake curl tar libtool libc-dev g++ go git protobuf
      - go get -v google.golang.org/grpc
      - make

  triggle-build-protoc:
    image: plugins/downstream
    fork: true
    repositories:
      - vaniila/protoc
    secrets: [ downstream_server, downstream_token ]
