workspace:
  base: /go
  path: src/github.com/vaniila/protobuf

pipeline:

  build-protobuf:
    image: golang:${GO_VERSION}
    commands:
      - apt-get update
      - apt-get install protobuf-compiler -y
      - go get -v ./...
      - make

  triggle-build-protoc:
    image: plugins/downstream
    fork: true
    repositories:
      - vaniila/protoc
    secrets: [ downstream_server, downstream_token ]
    when:
      matrix:
        GO_VERSION: 1.9

matrix:
  GO_VERSION:
    - 1.9
    - 1.8
