// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: combos/unmarshaler/one.proto

/*
	Package one is a generated protocol buffer package.

	It is generated from these files:
		combos/unmarshaler/one.proto

	It has these top-level messages:
		Subby
		SampleOneOf
*/
package one

import proto "github.com/vaniila/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/vaniila/protobuf/gogoproto"

import github_com_vaniila_protobuf_protoc_gen_gogo_descriptor "github.com/vaniila/protobuf/protoc-gen-gogo/descriptor"
import github_com_vaniila_protobuf_proto "github.com/vaniila/protobuf/proto"
import compress_gzip "compress/gzip"
import bytes "bytes"
import io_ioutil "io/ioutil"

import strings "strings"
import reflect "reflect"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type Subby struct {
	Sub string `protobuf:"bytes,1,opt,name=sub,proto3" json:"sub,omitempty"`
}

func (m *Subby) Reset()                    { *m = Subby{} }
func (*Subby) ProtoMessage()               {}
func (*Subby) Descriptor() ([]byte, []int) { return fileDescriptorOne, []int{0} }

type SampleOneOf struct {
	// Types that are valid to be assigned to TestOneof:
	//	*SampleOneOf_Field1
	//	*SampleOneOf_Field2
	//	*SampleOneOf_Field3
	//	*SampleOneOf_Field4
	//	*SampleOneOf_Field5
	//	*SampleOneOf_Field6
	//	*SampleOneOf_Field7
	//	*SampleOneOf_Field8
	//	*SampleOneOf_Field9
	//	*SampleOneOf_Field10
	//	*SampleOneOf_Field11
	//	*SampleOneOf_Field12
	//	*SampleOneOf_Field13
	//	*SampleOneOf_Field14
	//	*SampleOneOf_Field15
	//	*SampleOneOf_SubMessage
	TestOneof isSampleOneOf_TestOneof `protobuf_oneof:"test_oneof"`
}

func (m *SampleOneOf) Reset()                    { *m = SampleOneOf{} }
func (*SampleOneOf) ProtoMessage()               {}
func (*SampleOneOf) Descriptor() ([]byte, []int) { return fileDescriptorOne, []int{1} }

type isSampleOneOf_TestOneof interface {
	isSampleOneOf_TestOneof()
	Equal(interface{}) bool
	VerboseEqual(interface{}) error
	Size() int
}

type SampleOneOf_Field1 struct {
	Field1 float64 `protobuf:"fixed64,1,opt,name=Field1,proto3,oneof"`
}
type SampleOneOf_Field2 struct {
	Field2 float32 `protobuf:"fixed32,2,opt,name=Field2,proto3,oneof"`
}
type SampleOneOf_Field3 struct {
	Field3 int32 `protobuf:"varint,3,opt,name=Field3,proto3,oneof"`
}
type SampleOneOf_Field4 struct {
	Field4 int64 `protobuf:"varint,4,opt,name=Field4,proto3,oneof"`
}
type SampleOneOf_Field5 struct {
	Field5 uint32 `protobuf:"varint,5,opt,name=Field5,proto3,oneof"`
}
type SampleOneOf_Field6 struct {
	Field6 uint64 `protobuf:"varint,6,opt,name=Field6,proto3,oneof"`
}
type SampleOneOf_Field7 struct {
	Field7 int32 `protobuf:"zigzag32,7,opt,name=Field7,proto3,oneof"`
}
type SampleOneOf_Field8 struct {
	Field8 int64 `protobuf:"zigzag64,8,opt,name=Field8,proto3,oneof"`
}
type SampleOneOf_Field9 struct {
	Field9 uint32 `protobuf:"fixed32,9,opt,name=Field9,proto3,oneof"`
}
type SampleOneOf_Field10 struct {
	Field10 int32 `protobuf:"fixed32,10,opt,name=Field10,proto3,oneof"`
}
type SampleOneOf_Field11 struct {
	Field11 uint64 `protobuf:"fixed64,11,opt,name=Field11,proto3,oneof"`
}
type SampleOneOf_Field12 struct {
	Field12 int64 `protobuf:"fixed64,12,opt,name=Field12,proto3,oneof"`
}
type SampleOneOf_Field13 struct {
	Field13 bool `protobuf:"varint,13,opt,name=Field13,proto3,oneof"`
}
type SampleOneOf_Field14 struct {
	Field14 string `protobuf:"bytes,14,opt,name=Field14,proto3,oneof"`
}
type SampleOneOf_Field15 struct {
	Field15 []byte `protobuf:"bytes,15,opt,name=Field15,proto3,oneof"`
}
type SampleOneOf_SubMessage struct {
	SubMessage *Subby `protobuf:"bytes,16,opt,name=sub_message,json=subMessage,oneof"`
}

func (*SampleOneOf_Field1) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field2) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field3) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field4) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field5) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field6) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field7) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field8) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field9) isSampleOneOf_TestOneof()     {}
func (*SampleOneOf_Field10) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field11) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field12) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field13) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field14) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_Field15) isSampleOneOf_TestOneof()    {}
func (*SampleOneOf_SubMessage) isSampleOneOf_TestOneof() {}

func (m *SampleOneOf) GetTestOneof() isSampleOneOf_TestOneof {
	if m != nil {
		return m.TestOneof
	}
	return nil
}

func (m *SampleOneOf) GetField1() float64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field1); ok {
		return x.Field1
	}
	return 0
}

func (m *SampleOneOf) GetField2() float32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field2); ok {
		return x.Field2
	}
	return 0
}

func (m *SampleOneOf) GetField3() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field3); ok {
		return x.Field3
	}
	return 0
}

func (m *SampleOneOf) GetField4() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field4); ok {
		return x.Field4
	}
	return 0
}

func (m *SampleOneOf) GetField5() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field5); ok {
		return x.Field5
	}
	return 0
}

func (m *SampleOneOf) GetField6() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field6); ok {
		return x.Field6
	}
	return 0
}

func (m *SampleOneOf) GetField7() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field7); ok {
		return x.Field7
	}
	return 0
}

func (m *SampleOneOf) GetField8() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field8); ok {
		return x.Field8
	}
	return 0
}

func (m *SampleOneOf) GetField9() uint32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field9); ok {
		return x.Field9
	}
	return 0
}

func (m *SampleOneOf) GetField10() int32 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field10); ok {
		return x.Field10
	}
	return 0
}

func (m *SampleOneOf) GetField11() uint64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field11); ok {
		return x.Field11
	}
	return 0
}

func (m *SampleOneOf) GetField12() int64 {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field12); ok {
		return x.Field12
	}
	return 0
}

func (m *SampleOneOf) GetField13() bool {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field13); ok {
		return x.Field13
	}
	return false
}

func (m *SampleOneOf) GetField14() string {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field14); ok {
		return x.Field14
	}
	return ""
}

func (m *SampleOneOf) GetField15() []byte {
	if x, ok := m.GetTestOneof().(*SampleOneOf_Field15); ok {
		return x.Field15
	}
	return nil
}

func (m *SampleOneOf) GetSubMessage() *Subby {
	if x, ok := m.GetTestOneof().(*SampleOneOf_SubMessage); ok {
		return x.SubMessage
	}
	return nil
}

// XXX_OneofFuncs is for the internal use of the proto package.
func (*SampleOneOf) XXX_OneofFuncs() (func(msg proto.Message, b *proto.Buffer) error, func(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error), func(msg proto.Message) (n int), []interface{}) {
	return _SampleOneOf_OneofMarshaler, _SampleOneOf_OneofUnmarshaler, _SampleOneOf_OneofSizer, []interface{}{
		(*SampleOneOf_Field1)(nil),
		(*SampleOneOf_Field2)(nil),
		(*SampleOneOf_Field3)(nil),
		(*SampleOneOf_Field4)(nil),
		(*SampleOneOf_Field5)(nil),
		(*SampleOneOf_Field6)(nil),
		(*SampleOneOf_Field7)(nil),
		(*SampleOneOf_Field8)(nil),
		(*SampleOneOf_Field9)(nil),
		(*SampleOneOf_Field10)(nil),
		(*SampleOneOf_Field11)(nil),
		(*SampleOneOf_Field12)(nil),
		(*SampleOneOf_Field13)(nil),
		(*SampleOneOf_Field14)(nil),
		(*SampleOneOf_Field15)(nil),
		(*SampleOneOf_SubMessage)(nil),
	}
}

func _SampleOneOf_OneofMarshaler(msg proto.Message, b *proto.Buffer) error {
	m := msg.(*SampleOneOf)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *SampleOneOf_Field1:
		_ = b.EncodeVarint(1<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(math.Float64bits(x.Field1))
	case *SampleOneOf_Field2:
		_ = b.EncodeVarint(2<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(math.Float32bits(x.Field2)))
	case *SampleOneOf_Field3:
		_ = b.EncodeVarint(3<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field3))
	case *SampleOneOf_Field4:
		_ = b.EncodeVarint(4<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field4))
	case *SampleOneOf_Field5:
		_ = b.EncodeVarint(5<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field5))
	case *SampleOneOf_Field6:
		_ = b.EncodeVarint(6<<3 | proto.WireVarint)
		_ = b.EncodeVarint(uint64(x.Field6))
	case *SampleOneOf_Field7:
		_ = b.EncodeVarint(7<<3 | proto.WireVarint)
		_ = b.EncodeZigzag32(uint64(x.Field7))
	case *SampleOneOf_Field8:
		_ = b.EncodeVarint(8<<3 | proto.WireVarint)
		_ = b.EncodeZigzag64(uint64(x.Field8))
	case *SampleOneOf_Field9:
		_ = b.EncodeVarint(9<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(x.Field9))
	case *SampleOneOf_Field10:
		_ = b.EncodeVarint(10<<3 | proto.WireFixed32)
		_ = b.EncodeFixed32(uint64(x.Field10))
	case *SampleOneOf_Field11:
		_ = b.EncodeVarint(11<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(uint64(x.Field11))
	case *SampleOneOf_Field12:
		_ = b.EncodeVarint(12<<3 | proto.WireFixed64)
		_ = b.EncodeFixed64(uint64(x.Field12))
	case *SampleOneOf_Field13:
		t := uint64(0)
		if x.Field13 {
			t = 1
		}
		_ = b.EncodeVarint(13<<3 | proto.WireVarint)
		_ = b.EncodeVarint(t)
	case *SampleOneOf_Field14:
		_ = b.EncodeVarint(14<<3 | proto.WireBytes)
		_ = b.EncodeStringBytes(x.Field14)
	case *SampleOneOf_Field15:
		_ = b.EncodeVarint(15<<3 | proto.WireBytes)
		_ = b.EncodeRawBytes(x.Field15)
	case *SampleOneOf_SubMessage:
		_ = b.EncodeVarint(16<<3 | proto.WireBytes)
		if err := b.EncodeMessage(x.SubMessage); err != nil {
			return err
		}
	case nil:
	default:
		return fmt.Errorf("SampleOneOf.TestOneof has unexpected type %T", x)
	}
	return nil
}

func _SampleOneOf_OneofUnmarshaler(msg proto.Message, tag, wire int, b *proto.Buffer) (bool, error) {
	m := msg.(*SampleOneOf)
	switch tag {
	case 1: // test_oneof.Field1
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field1{math.Float64frombits(x)}
		return true, err
	case 2: // test_oneof.Field2
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field2{math.Float32frombits(uint32(x))}
		return true, err
	case 3: // test_oneof.Field3
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field3{int32(x)}
		return true, err
	case 4: // test_oneof.Field4
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field4{int64(x)}
		return true, err
	case 5: // test_oneof.Field5
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field5{uint32(x)}
		return true, err
	case 6: // test_oneof.Field6
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field6{x}
		return true, err
	case 7: // test_oneof.Field7
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag32()
		m.TestOneof = &SampleOneOf_Field7{int32(x)}
		return true, err
	case 8: // test_oneof.Field8
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeZigzag64()
		m.TestOneof = &SampleOneOf_Field8{int64(x)}
		return true, err
	case 9: // test_oneof.Field9
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field9{uint32(x)}
		return true, err
	case 10: // test_oneof.Field10
		if wire != proto.WireFixed32 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed32()
		m.TestOneof = &SampleOneOf_Field10{int32(x)}
		return true, err
	case 11: // test_oneof.Field11
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field11{x}
		return true, err
	case 12: // test_oneof.Field12
		if wire != proto.WireFixed64 {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeFixed64()
		m.TestOneof = &SampleOneOf_Field12{int64(x)}
		return true, err
	case 13: // test_oneof.Field13
		if wire != proto.WireVarint {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeVarint()
		m.TestOneof = &SampleOneOf_Field13{x != 0}
		return true, err
	case 14: // test_oneof.Field14
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeStringBytes()
		m.TestOneof = &SampleOneOf_Field14{x}
		return true, err
	case 15: // test_oneof.Field15
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		x, err := b.DecodeRawBytes(true)
		m.TestOneof = &SampleOneOf_Field15{x}
		return true, err
	case 16: // test_oneof.sub_message
		if wire != proto.WireBytes {
			return true, proto.ErrInternalBadWireType
		}
		msg := new(Subby)
		err := b.DecodeMessage(msg)
		m.TestOneof = &SampleOneOf_SubMessage{msg}
		return true, err
	default:
		return false, nil
	}
}

func _SampleOneOf_OneofSizer(msg proto.Message) (n int) {
	m := msg.(*SampleOneOf)
	// test_oneof
	switch x := m.TestOneof.(type) {
	case *SampleOneOf_Field1:
		n += proto.SizeVarint(1<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field2:
		n += proto.SizeVarint(2<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field3:
		n += proto.SizeVarint(3<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field3))
	case *SampleOneOf_Field4:
		n += proto.SizeVarint(4<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field4))
	case *SampleOneOf_Field5:
		n += proto.SizeVarint(5<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field5))
	case *SampleOneOf_Field6:
		n += proto.SizeVarint(6<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(x.Field6))
	case *SampleOneOf_Field7:
		n += proto.SizeVarint(7<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64((uint32(x.Field7) << 1) ^ uint32((int32(x.Field7) >> 31))))
	case *SampleOneOf_Field8:
		n += proto.SizeVarint(8<<3 | proto.WireVarint)
		n += proto.SizeVarint(uint64(uint64(x.Field8<<1) ^ uint64((int64(x.Field8) >> 63))))
	case *SampleOneOf_Field9:
		n += proto.SizeVarint(9<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field10:
		n += proto.SizeVarint(10<<3 | proto.WireFixed32)
		n += 4
	case *SampleOneOf_Field11:
		n += proto.SizeVarint(11<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field12:
		n += proto.SizeVarint(12<<3 | proto.WireFixed64)
		n += 8
	case *SampleOneOf_Field13:
		n += proto.SizeVarint(13<<3 | proto.WireVarint)
		n += 1
	case *SampleOneOf_Field14:
		n += proto.SizeVarint(14<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Field14)))
		n += len(x.Field14)
	case *SampleOneOf_Field15:
		n += proto.SizeVarint(15<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(len(x.Field15)))
		n += len(x.Field15)
	case *SampleOneOf_SubMessage:
		s := proto.Size(x.SubMessage)
		n += proto.SizeVarint(16<<3 | proto.WireBytes)
		n += proto.SizeVarint(uint64(s))
		n += s
	case nil:
	default:
		panic(fmt.Sprintf("proto: unexpected type %T in oneof", x))
	}
	return n
}

func init() {
	proto.RegisterType((*Subby)(nil), "one.Subby")
	proto.RegisterType((*SampleOneOf)(nil), "one.SampleOneOf")
}
func (this *Subby) Description() (desc *github_com_vaniila_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func (this *SampleOneOf) Description() (desc *github_com_vaniila_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	return OneDescription()
}
func OneDescription() (desc *github_com_vaniila_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet) {
	d := &github_com_vaniila_protobuf_protoc_gen_gogo_descriptor.FileDescriptorSet{}
	var gzipped = []byte{
		// 3957 bytes of a gzipped FileDescriptorSet
		0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x5a, 0x5d, 0x70, 0xe3, 0xd6,
		0x75, 0x16, 0xf8, 0x23, 0x91, 0x87, 0x14, 0x05, 0x41, 0xf2, 0x2e, 0x56, 0xb6, 0xb9, 0x5a, 0xd9,
		0xae, 0x65, 0xbb, 0x91, 0x6c, 0xed, 0x6a, 0x7f, 0xb8, 0x4d, 0x3c, 0x94, 0xc4, 0xd5, 0x6a, 0x2b,
		0x89, 0x0c, 0x28, 0xc5, 0xeb, 0xf4, 0x01, 0x03, 0x82, 0x97, 0x14, 0x76, 0x41, 0x00, 0x06, 0xc0,
		0x5d, 0xcb, 0x4f, 0xdb, 0x71, 0x7f, 0x26, 0xd3, 0xe9, 0x7f, 0x67, 0x9a, 0xb8, 0xb6, 0xdb, 0x66,
		0xa6, 0x75, 0x92, 0xfe, 0x25, 0x75, 0x9b, 0xa6, 0x7d, 0xea, 0x4b, 0x5a, 0x3f, 0x75, 0x92, 0xb7,
		0x3e, 0xe4, 0xc1, 0xab, 0x7a, 0xa6, 0x69, 0xe3, 0xb6, 0x6e, 0xbb, 0x33, 0xcd, 0x8c, 0x5f, 0x3a,
		0xf7, 0x0f, 0x00, 0x7f, 0xb4, 0xa0, 0x32, 0xe3, 0xe4, 0x49, 0xc2, 0x39, 0xe7, 0xfb, 0x70, 0xee,
		0xb9, 0xe7, 0xde, 0x73, 0xee, 0x05, 0xe1, 0x07, 0x17, 0x61, 0xbe, 0x6d, 0xdb, 0x6d, 0x13, 0x2d,
		0x3b, 0xae, 0xed, 0xdb, 0x8d, 0x6e, 0x6b, 0xb9, 0x89, 0x3c, 0xdd, 0x35, 0x1c, 0xdf, 0x76, 0x97,
		0x88, 0x4c, 0x9a, 0xa2, 0x16, 0x4b, 0xdc, 0x62, 0x61, 0x07, 0xa6, 0xaf, 0x19, 0x26, 0xda, 0x08,
		0x0c, 0xeb, 0xc8, 0x97, 0x2e, 0x43, 0xaa, 0x65, 0x98, 0x48, 0x16, 0xe6, 0x93, 0x8b, 0xb9, 0x95,
		0x27, 0x97, 0xfa, 0x40, 0x4b, 0xbd, 0x88, 0x1a, 0x16, 0x2b, 0x04, 0xb1, 0xf0, 0x41, 0x0a, 0x66,
		0x86, 0x68, 0x25, 0x09, 0x52, 0x96, 0xd6, 0xc1, 0x8c, 0xc2, 0x62, 0x56, 0x21, 0xff, 0x4b, 0x32,
		0x4c, 0x38, 0x9a, 0x7e, 0x5b, 0x6b, 0x23, 0x39, 0x41, 0xc4, 0xfc, 0x51, 0x2a, 0x02, 0x34, 0x91,
		0x83, 0xac, 0x26, 0xb2, 0xf4, 0x43, 0x39, 0x39, 0x9f, 0x5c, 0xcc, 0x2a, 0x11, 0x89, 0xf4, 0x1c,
		0x4c, 0x3b, 0xdd, 0x86, 0x69, 0xe8, 0x6a, 0xc4, 0x0c, 0xe6, 0x93, 0x8b, 0x69, 0x45, 0xa4, 0x8a,
		0x8d, 0xd0, 0xf8, 0x69, 0x98, 0xba, 0x8b, 0xb4, 0xdb, 0x51, 0xd3, 0x1c, 0x31, 0x2d, 0x60, 0x71,
		0xc4, 0x70, 0x1d, 0xf2, 0x1d, 0xe4, 0x79, 0x5a, 0x1b, 0xa9, 0xfe, 0xa1, 0x83, 0xe4, 0x14, 0x19,
		0xfd, 0xfc, 0xc0, 0xe8, 0xfb, 0x47, 0x9e, 0x63, 0xa8, 0xbd, 0x43, 0x07, 0x49, 0x65, 0xc8, 0x22,
		0xab, 0xdb, 0xa1, 0x0c, 0xe9, 0x63, 0xe2, 0x57, 0xb1, 0xba, 0x9d, 0x7e, 0x96, 0x0c, 0x86, 0x31,
		0x8a, 0x09, 0x0f, 0xb9, 0x77, 0x0c, 0x1d, 0xc9, 0xe3, 0x84, 0xe0, 0xe9, 0x01, 0x82, 0x3a, 0xd5,
		0xf7, 0x73, 0x70, 0x9c, 0xb4, 0x0e, 0x59, 0xf4, 0xaa, 0x8f, 0x2c, 0xcf, 0xb0, 0x2d, 0x79, 0x82,
		0x90, 0x3c, 0x35, 0x64, 0x16, 0x91, 0xd9, 0xec, 0xa7, 0x08, 0x71, 0xd2, 0x45, 0x98, 0xb0, 0x1d,
		0xdf, 0xb0, 0x2d, 0x4f, 0xce, 0xcc, 0x0b, 0x8b, 0xb9, 0x95, 0xc7, 0x86, 0x26, 0x42, 0x95, 0xda,
		0x28, 0xdc, 0x58, 0xda, 0x02, 0xd1, 0xb3, 0xbb, 0xae, 0x8e, 0x54, 0xdd, 0x6e, 0x22, 0xd5, 0xb0,
		0x5a, 0xb6, 0x9c, 0x25, 0x04, 0x67, 0x07, 0x07, 0x42, 0x0c, 0xd7, 0xed, 0x26, 0xda, 0xb2, 0x5a,
		0xb6, 0x52, 0xf0, 0x7a, 0x9e, 0xa5, 0x53, 0x30, 0xee, 0x1d, 0x5a, 0xbe, 0xf6, 0xaa, 0x9c, 0x27,
		0x19, 0xc2, 0x9e, 0x16, 0xfe, 0x2f, 0x0d, 0x53, 0xa3, 0xa4, 0xd8, 0x55, 0x48, 0xb7, 0xf0, 0x28,
		0xe5, 0xc4, 0x49, 0x62, 0x40, 0x31, 0xbd, 0x41, 0x1c, 0xff, 0x11, 0x83, 0x58, 0x86, 0x9c, 0x85,
		0x3c, 0x1f, 0x35, 0x69, 0x46, 0x24, 0x47, 0xcc, 0x29, 0xa0, 0xa0, 0xc1, 0x94, 0x4a, 0xfd, 0x48,
		0x29, 0x75, 0x13, 0xa6, 0x02, 0x97, 0x54, 0x57, 0xb3, 0xda, 0x3c, 0x37, 0x97, 0xe3, 0x3c, 0x59,
		0xaa, 0x70, 0x9c, 0x82, 0x61, 0x4a, 0x01, 0xf5, 0x3c, 0x4b, 0x1b, 0x00, 0xb6, 0x85, 0xec, 0x96,
		0xda, 0x44, 0xba, 0x29, 0x67, 0x8e, 0x89, 0x52, 0x15, 0x9b, 0x0c, 0x44, 0xc9, 0xa6, 0x52, 0xdd,
		0x94, 0xae, 0x84, 0xa9, 0x36, 0x71, 0x4c, 0xa6, 0xec, 0xd0, 0x45, 0x36, 0x90, 0x6d, 0xfb, 0x50,
		0x70, 0x11, 0xce, 0x7b, 0xd4, 0x64, 0x23, 0xcb, 0x12, 0x27, 0x96, 0x62, 0x47, 0xa6, 0x30, 0x18,
		0x1d, 0xd8, 0xa4, 0x1b, 0x7d, 0x94, 0x9e, 0x80, 0x40, 0xa0, 0x92, 0xb4, 0x02, 0xb2, 0x0b, 0xe5,
		0xb9, 0x70, 0x57, 0xeb, 0xa0, 0xb9, 0xcb, 0x50, 0xe8, 0x0d, 0x8f, 0x34, 0x0b, 0x69, 0xcf, 0xd7,
		0x5c, 0x9f, 0x64, 0x61, 0x5a, 0xa1, 0x0f, 0x92, 0x08, 0x49, 0x64, 0x35, 0xc9, 0x2e, 0x97, 0x56,
		0xf0, 0xbf, 0x73, 0x97, 0x60, 0xb2, 0xe7, 0xf5, 0xa3, 0x02, 0x17, 0xbe, 0x38, 0x0e, 0xb3, 0xc3,
		0x72, 0x6e, 0x68, 0xfa, 0x9f, 0x82, 0x71, 0xab, 0xdb, 0x69, 0x20, 0x57, 0x4e, 0x12, 0x06, 0xf6,
		0x24, 0x95, 0x21, 0x6d, 0x6a, 0x0d, 0x64, 0xca, 0xa9, 0x79, 0x61, 0xb1, 0xb0, 0xf2, 0xdc, 0x48,
		0x59, 0xbd, 0xb4, 0x8d, 0x21, 0x0a, 0x45, 0x4a, 0x9f, 0x81, 0x14, 0xdb, 0xe2, 0x30, 0xc3, 0xb3,
		0xa3, 0x31, 0xe0, 0x5c, 0x54, 0x08, 0x4e, 0x7a, 0x14, 0xb2, 0xf8, 0x2f, 0x8d, 0xed, 0x38, 0xf1,
		0x39, 0x83, 0x05, 0x38, 0xae, 0xd2, 0x1c, 0x64, 0x48, 0x9a, 0x35, 0x11, 0x2f, 0x0d, 0xc1, 0x33,
		0x9e, 0x98, 0x26, 0x6a, 0x69, 0x5d, 0xd3, 0x57, 0xef, 0x68, 0x66, 0x17, 0x91, 0x84, 0xc9, 0x2a,
		0x79, 0x26, 0xfc, 0x1c, 0x96, 0x49, 0x67, 0x21, 0x47, 0xb3, 0xd2, 0xb0, 0x9a, 0xe8, 0x55, 0xb2,
		0xfb, 0xa4, 0x15, 0x9a, 0xa8, 0x5b, 0x58, 0x82, 0x5f, 0x7f, 0xcb, 0xb3, 0x2d, 0x3e, 0xb5, 0xe4,
		0x15, 0x58, 0x40, 0x5e, 0x7f, 0xa9, 0x7f, 0xe3, 0x7b, 0x7c, 0xf8, 0xf0, 0xfa, 0x73, 0x71, 0xe1,
		0x9b, 0x09, 0x48, 0x91, 0xf5, 0x36, 0x05, 0xb9, 0xbd, 0x97, 0x6b, 0x15, 0x75, 0xa3, 0xba, 0xbf,
		0xb6, 0x5d, 0x11, 0x05, 0xa9, 0x00, 0x40, 0x04, 0xd7, 0xb6, 0xab, 0xe5, 0x3d, 0x31, 0x11, 0x3c,
		0x6f, 0xed, 0xee, 0x5d, 0xbc, 0x20, 0x26, 0x03, 0xc0, 0x3e, 0x15, 0xa4, 0xa2, 0x06, 0xe7, 0x57,
		0xc4, 0xb4, 0x24, 0x42, 0x9e, 0x12, 0x6c, 0xdd, 0xac, 0x6c, 0x5c, 0xbc, 0x20, 0x8e, 0xf7, 0x4a,
		0xce, 0xaf, 0x88, 0x13, 0xd2, 0x24, 0x64, 0x89, 0x64, 0xad, 0x5a, 0xdd, 0x16, 0x33, 0x01, 0x67,
		0x7d, 0x4f, 0xd9, 0xda, 0xdd, 0x14, 0xb3, 0x01, 0xe7, 0xa6, 0x52, 0xdd, 0xaf, 0x89, 0x10, 0x30,
		0xec, 0x54, 0xea, 0xf5, 0xf2, 0x66, 0x45, 0xcc, 0x05, 0x16, 0x6b, 0x2f, 0xef, 0x55, 0xea, 0x62,
		0xbe, 0xc7, 0xad, 0xf3, 0x2b, 0xe2, 0x64, 0xf0, 0x8a, 0xca, 0xee, 0xfe, 0x8e, 0x58, 0x90, 0xa6,
		0x61, 0x92, 0xbe, 0x82, 0x3b, 0x31, 0xd5, 0x27, 0xba, 0x78, 0x41, 0x14, 0x43, 0x47, 0x28, 0xcb,
		0x74, 0x8f, 0xe0, 0xe2, 0x05, 0x51, 0x5a, 0x58, 0x87, 0x34, 0xc9, 0x2e, 0x49, 0x82, 0xc2, 0x76,
		0x79, 0xad, 0xb2, 0xad, 0x56, 0x6b, 0x7b, 0x5b, 0xd5, 0xdd, 0xf2, 0xb6, 0x28, 0x84, 0x32, 0xa5,
		0xf2, 0xd9, 0xfd, 0x2d, 0xa5, 0xb2, 0x21, 0x26, 0xa2, 0xb2, 0x5a, 0xa5, 0xbc, 0x57, 0xd9, 0x10,
		0x93, 0x0b, 0x3a, 0xcc, 0x0e, 0xdb, 0x67, 0x86, 0xae, 0x8c, 0xc8, 0x14, 0x27, 0x8e, 0x99, 0x62,
		0xc2, 0x35, 0x30, 0xc5, 0x5f, 0x16, 0x60, 0x66, 0xc8, 0x5e, 0x3b, 0xf4, 0x25, 0x2f, 0x42, 0x9a,
		0xa6, 0x28, 0xad, 0x3e, 0xcf, 0x0c, 0xdd, 0xb4, 0x49, 0xc2, 0x0e, 0x54, 0x20, 0x82, 0x8b, 0x56,
		0xe0, 0xe4, 0x31, 0x15, 0x18, 0x53, 0x0c, 0x38, 0xf9, 0xba, 0x00, 0xf2, 0x71, 0xdc, 0x31, 0x1b,
		0x45, 0xa2, 0x67, 0xa3, 0xb8, 0xda, 0xef, 0xc0, 0xb9, 0xe3, 0xc7, 0x30, 0xe0, 0xc5, 0x3b, 0x02,
		0x9c, 0x1a, 0xde, 0xa8, 0x0c, 0xf5, 0xe1, 0x33, 0x30, 0xde, 0x41, 0xfe, 0x81, 0xcd, 0x8b, 0xf5,
		0x4f, 0x0d, 0x29, 0x01, 0x58, 0xdd, 0x1f, 0x2b, 0x86, 0x8a, 0xd6, 0x90, 0xe4, 0x71, 0xdd, 0x06,
		0xf5, 0x66, 0xc0, 0xd3, 0x2f, 0x24, 0xe0, 0x91, 0xa1, 0xe4, 0x43, 0x1d, 0x7d, 0x1c, 0xc0, 0xb0,
		0x9c, 0xae, 0x4f, 0x0b, 0x32, 0xdd, 0x9f, 0xb2, 0x44, 0x42, 0xd6, 0x3e, 0xde, 0x7b, 0xba, 0x7e,
		0xa0, 0x4f, 0x12, 0x3d, 0x50, 0x11, 0x31, 0xb8, 0x1c, 0x3a, 0x9a, 0x22, 0x8e, 0x16, 0x8f, 0x19,
		0xe9, 0x40, 0xad, 0x7b, 0x1e, 0x44, 0xdd, 0x34, 0x90, 0xe5, 0xab, 0x9e, 0xef, 0x22, 0xad, 0x63,
		0x58, 0x6d, 0xb2, 0x01, 0x67, 0x4a, 0xe9, 0x96, 0x66, 0x7a, 0x48, 0x99, 0xa2, 0xea, 0x3a, 0xd7,
		0x62, 0x04, 0xa9, 0x32, 0x6e, 0x04, 0x31, 0xde, 0x83, 0xa0, 0xea, 0x00, 0xb1, 0xf0, 0x6e, 0x06,
		0x72, 0x91, 0xb6, 0x4e, 0x3a, 0x07, 0xf9, 0x5b, 0xda, 0x1d, 0x4d, 0xe5, 0xad, 0x3a, 0x8d, 0x44,
		0x0e, 0xcb, 0x6a, 0xac, 0x5d, 0x7f, 0x1e, 0x66, 0x89, 0x89, 0xdd, 0xf5, 0x91, 0xab, 0xea, 0xa6,
		0xe6, 0x79, 0x24, 0x68, 0x19, 0x62, 0x2a, 0x61, 0x5d, 0x15, 0xab, 0xd6, 0xb9, 0x46, 0x5a, 0x85,
		0x19, 0x82, 0xe8, 0x74, 0x4d, 0xdf, 0x70, 0x4c, 0xa4, 0xe2, 0xc3, 0x83, 0x47, 0x36, 0xe2, 0xc0,
		0xb3, 0x69, 0x6c, 0xb1, 0xc3, 0x0c, 0xb0, 0x47, 0x9e, 0xb4, 0x01, 0x8f, 0x13, 0x58, 0x1b, 0x59,
		0xc8, 0xd5, 0x7c, 0xa4, 0xa2, 0x57, 0xba, 0x9a, 0xe9, 0xa9, 0x9a, 0xd5, 0x54, 0x0f, 0x34, 0xef,
		0x40, 0x9e, 0xc5, 0x04, 0x6b, 0x09, 0x59, 0x50, 0xce, 0x60, 0xc3, 0x4d, 0x66, 0x57, 0x21, 0x66,
		0x65, 0xab, 0x79, 0x5d, 0xf3, 0x0e, 0xa4, 0x12, 0x9c, 0x22, 0x2c, 0x9e, 0xef, 0x1a, 0x56, 0x5b,
		0xd5, 0x0f, 0x90, 0x7e, 0x5b, 0xed, 0xfa, 0xad, 0xcb, 0xf2, 0xa3, 0xd1, 0xf7, 0x13, 0x0f, 0xeb,
		0xc4, 0x66, 0x1d, 0x9b, 0xec, 0xfb, 0xad, 0xcb, 0x52, 0x1d, 0xf2, 0x78, 0x32, 0x3a, 0xc6, 0x6b,
		0x48, 0x6d, 0xd9, 0x2e, 0xa9, 0x2c, 0x85, 0x21, 0x2b, 0x3b, 0x12, 0xc1, 0xa5, 0x2a, 0x03, 0xec,
		0xd8, 0x4d, 0x54, 0x4a, 0xd7, 0x6b, 0x95, 0xca, 0x86, 0x92, 0xe3, 0x2c, 0xd7, 0x6c, 0x17, 0x27,
		0x54, 0xdb, 0x0e, 0x02, 0x9c, 0xa3, 0x09, 0xd5, 0xb6, 0x79, 0x78, 0x57, 0x61, 0x46, 0xd7, 0xe9,
		0x98, 0x0d, 0x5d, 0x65, 0x2d, 0xbe, 0x27, 0x8b, 0x3d, 0xc1, 0xd2, 0xf5, 0x4d, 0x6a, 0xc0, 0x72,
		0xdc, 0x93, 0xae, 0xc0, 0x23, 0x61, 0xb0, 0xa2, 0xc0, 0xe9, 0x81, 0x51, 0xf6, 0x43, 0x57, 0x61,
		0xc6, 0x39, 0x1c, 0x04, 0x4a, 0x3d, 0x6f, 0x74, 0x0e, 0xfb, 0x61, 0x97, 0x60, 0xd6, 0x39, 0x70,
		0x06, 0x71, 0x33, 0x51, 0x9c, 0xe4, 0x1c, 0x38, 0xfd, 0xc0, 0xa7, 0xc8, 0x79, 0xcf, 0x45, 0xba,
		0xe6, 0xa3, 0xa6, 0x7c, 0x3a, 0x6a, 0x1e, 0x51, 0x48, 0xcb, 0x20, 0xea, 0xba, 0x8a, 0x2c, 0xad,
		0x61, 0x22, 0x55, 0x73, 0x91, 0xa5, 0x79, 0xf2, 0xd9, 0xa8, 0x71, 0x41, 0xd7, 0x2b, 0x44, 0x5b,
		0x26, 0x4a, 0xe9, 0x59, 0x98, 0xb6, 0x1b, 0xb7, 0x74, 0x9a, 0x92, 0xaa, 0xe3, 0xa2, 0x96, 0xf1,
		0xaa, 0xfc, 0x24, 0x89, 0xef, 0x14, 0x56, 0x90, 0x84, 0xac, 0x11, 0xb1, 0xf4, 0x0c, 0x88, 0xba,
		0x77, 0xa0, 0xb9, 0x0e, 0xe9, 0x09, 0x3c, 0x47, 0xd3, 0x91, 0xfc, 0x14, 0x35, 0xa5, 0xf2, 0x5d,
		0x2e, 0xc6, 0x4b, 0xc2, 0xbb, 0x6b, 0xb4, 0x7c, 0xce, 0xf8, 0x34, 0x5d, 0x12, 0x44, 0xc6, 0xd8,
		0x16, 0x41, 0xc4, 0xa1, 0xe8, 0x79, 0xf1, 0x22, 0x31, 0x2b, 0x38, 0x07, 0x4e, 0xf4, 0xbd, 0x4f,
		0xc0, 0x24, 0xb6, 0x0c, 0x5f, 0xfa, 0x0c, 0xed, 0x67, 0x9c, 0x83, 0xc8, 0x1b, 0x6f, 0xc2, 0x6c,
		0xd7, 0x32, 0x2c, 0x1f, 0xb9, 0x8e, 0x8b, 0xf0, 0x61, 0x82, 0xee, 0x08, 0xf2, 0xbf, 0x4e, 0x1c,
		0x73, 0x1c, 0xd8, 0x8f, 0x5a, 0xd3, 0x44, 0x54, 0x66, 0xba, 0x83, 0xc2, 0x85, 0x12, 0xe4, 0xa3,
		0xf9, 0x29, 0x65, 0x81, 0x66, 0xa8, 0x28, 0xe0, 0x5a, 0xbf, 0x5e, 0xdd, 0xc0, 0x55, 0xfa, 0xf3,
		0x15, 0x31, 0x81, 0xbb, 0x85, 0xed, 0xad, 0xbd, 0x8a, 0xaa, 0xec, 0xef, 0xee, 0x6d, 0xed, 0x54,
		0xc4, 0xe4, 0xb3, 0xd9, 0xcc, 0xf7, 0x27, 0xc4, 0x7b, 0xf7, 0xee, 0xdd, 0x4b, 0x2c, 0x7c, 0x3b,
		0x01, 0x85, 0xde, 0x0e, 0x5d, 0xfa, 0x19, 0x38, 0xcd, 0x8f, 0xd3, 0x1e, 0xf2, 0xd5, 0xbb, 0x86,
		0x4b, 0x96, 0x4c, 0x47, 0xa3, 0x3d, 0x6e, 0x30, 0x69, 0xb3, 0xcc, 0xaa, 0x8e, 0xfc, 0x97, 0x0c,
		0x17, 0x2f, 0x88, 0x8e, 0xe6, 0x4b, 0xdb, 0x70, 0xd6, 0xb2, 0x55, 0xcf, 0xd7, 0xac, 0xa6, 0xe6,
		0x36, 0xd5, 0xf0, 0x22, 0x43, 0xd5, 0x74, 0x1d, 0x79, 0x9e, 0x4d, 0x4b, 0x55, 0xc0, 0xf2, 0x98,
		0x65, 0xd7, 0x99, 0x71, 0xb8, 0x87, 0x97, 0x99, 0x69, 0x5f, 0x82, 0x25, 0x8f, 0x4b, 0xb0, 0x47,
		0x21, 0xdb, 0xd1, 0x1c, 0x15, 0x59, 0xbe, 0x7b, 0x48, 0xfa, 0xca, 0x8c, 0x92, 0xe9, 0x68, 0x4e,
		0x05, 0x3f, 0x7f, 0x72, 0x73, 0x10, 0x8d, 0xe3, 0xf7, 0x92, 0x90, 0x8f, 0xf6, 0x96, 0xb8, 0x55,
		0xd7, 0x49, 0x1d, 0x11, 0xc8, 0x4e, 0xf3, 0xc4, 0x43, 0x3b, 0xd1, 0xa5, 0x75, 0x5c, 0x60, 0x4a,
		0xe3, 0xb4, 0xe3, 0x53, 0x28, 0x12, 0x17, 0x77, 0xbc, 0xb7, 0x20, 0x7a, 0x8e, 0xc8, 0x28, 0xec,
		0x49, 0xda, 0x84, 0xf1, 0x5b, 0x1e, 0xe1, 0x1e, 0x27, 0xdc, 0x4f, 0x3e, 0x9c, 0xfb, 0x46, 0x9d,
		0x90, 0x67, 0x6f, 0xd4, 0xd5, 0xdd, 0xaa, 0xb2, 0x53, 0xde, 0x56, 0x18, 0x5c, 0x3a, 0x03, 0x29,
		0x53, 0x7b, 0xed, 0xb0, 0xb7, 0x14, 0x11, 0xd1, 0xa8, 0x81, 0x3f, 0x03, 0xa9, 0xbb, 0x48, 0xbb,
		0xdd, 0x5b, 0x00, 0x88, 0xe8, 0x13, 0x4c, 0xfd, 0x65, 0x48, 0x93, 0x78, 0x49, 0x00, 0x2c, 0x62,
		0xe2, 0x98, 0x94, 0x81, 0xd4, 0x7a, 0x55, 0xc1, 0xe9, 0x2f, 0x42, 0x9e, 0x4a, 0xd5, 0xda, 0x56,
		0x65, 0xbd, 0x22, 0x26, 0x16, 0x56, 0x61, 0x9c, 0x06, 0x01, 0x2f, 0x8d, 0x20, 0x0c, 0xe2, 0x18,
		0x7b, 0x64, 0x1c, 0x02, 0xd7, 0xee, 0xef, 0xac, 0x55, 0x14, 0x31, 0x11, 0x9d, 0x5e, 0x0f, 0xf2,
		0xd1, 0xb6, 0xf2, 0xc7, 0x93, 0x53, 0x7f, 0x27, 0x40, 0x2e, 0xd2, 0x26, 0xe2, 0x06, 0x45, 0x33,
		0x4d, 0xfb, 0xae, 0xaa, 0x99, 0x86, 0xe6, 0xb1, 0xa4, 0x00, 0x22, 0x2a, 0x63, 0xc9, 0xa8, 0x93,
		0xf6, 0x63, 0x71, 0xfe, 0x6d, 0x01, 0xc4, 0xfe, 0x16, 0xb3, 0xcf, 0x41, 0xe1, 0x27, 0xea, 0xe0,
		0x9b, 0x02, 0x14, 0x7a, 0xfb, 0xca, 0x3e, 0xf7, 0xce, 0xfd, 0x44, 0xdd, 0x7b, 0x3f, 0x01, 0x93,
		0x3d, 0xdd, 0xe4, 0xa8, 0xde, 0xbd, 0x02, 0xd3, 0x46, 0x13, 0x75, 0x1c, 0xdb, 0x47, 0x96, 0x7e,
		0xa8, 0x9a, 0xe8, 0x0e, 0x32, 0xe5, 0x05, 0xb2, 0x51, 0x2c, 0x3f, 0xbc, 0x5f, 0x5d, 0xda, 0x0a,
		0x71, 0xdb, 0x18, 0x56, 0x9a, 0xd9, 0xda, 0xa8, 0xec, 0xd4, 0xaa, 0x7b, 0x95, 0xdd, 0xf5, 0x97,
		0xd5, 0xfd, 0xdd, 0x9f, 0xdd, 0xad, 0xbe, 0xb4, 0xab, 0x88, 0x46, 0x9f, 0xd9, 0x27, 0xb8, 0xd4,
		0x6b, 0x20, 0xf6, 0x3b, 0x25, 0x9d, 0x86, 0x61, 0x6e, 0x89, 0x63, 0xd2, 0x0c, 0x4c, 0xed, 0x56,
		0xd5, 0xfa, 0xd6, 0x46, 0x45, 0xad, 0x5c, 0xbb, 0x56, 0x59, 0xdf, 0xab, 0xd3, 0x03, 0x7c, 0x60,
		0xbd, 0xd7, 0xbb, 0xa8, 0xdf, 0x48, 0xc2, 0xcc, 0x10, 0x4f, 0xa4, 0x32, 0x3b, 0x3b, 0xd0, 0xe3,
		0xcc, 0xa7, 0x46, 0xf1, 0x7e, 0x09, 0x97, 0xfc, 0x9a, 0xe6, 0xfa, 0xec, 0xa8, 0xf1, 0x0c, 0xe0,
		0x28, 0x59, 0xbe, 0xd1, 0x32, 0x90, 0xcb, 0xee, 0x3b, 0xe8, 0x81, 0x62, 0x2a, 0x94, 0xd3, 0x2b,
		0x8f, 0x9f, 0x06, 0xc9, 0xb1, 0x3d, 0xc3, 0x37, 0xee, 0x20, 0xd5, 0xb0, 0xf8, 0xe5, 0x08, 0x3e,
		0x60, 0xa4, 0x14, 0x91, 0x6b, 0xb6, 0x2c, 0x3f, 0xb0, 0xb6, 0x50, 0x5b, 0xeb, 0xb3, 0xc6, 0x1b,
		0x78, 0x52, 0x11, 0xb9, 0x26, 0xb0, 0x3e, 0x07, 0xf9, 0xa6, 0xdd, 0xc5, 0x5d, 0x17, 0xb5, 0xc3,
		0xf5, 0x42, 0x50, 0x72, 0x54, 0x16, 0x98, 0xb0, 0x7e, 0x3a, 0xbc, 0x95, 0xc9, 0x2b, 0x39, 0x2a,
		0xa3, 0x26, 0x4f, 0xc3, 0x94, 0xd6, 0x6e, 0xbb, 0x98, 0x9c, 0x13, 0xd1, 0x13, 0x42, 0x21, 0x10,
		0x13, 0xc3, 0xb9, 0x1b, 0x90, 0xe1, 0x71, 0xc0, 0x25, 0x19, 0x47, 0x42, 0x75, 0xe8, 0xdd, 0x58,
		0x62, 0x31, 0xab, 0x64, 0x2c, 0xae, 0x3c, 0x07, 0x79, 0xc3, 0x53, 0xc3, 0x4b, 0xda, 0xc4, 0x7c,
		0x62, 0x31, 0xa3, 0xe4, 0x0c, 0x2f, 0xb8, 0x95, 0x5b, 0x78, 0x27, 0x01, 0x85, 0xde, 0x4b, 0x66,
		0x69, 0x03, 0x32, 0xa6, 0xad, 0x6b, 0x24, 0xb5, 0xe8, 0x17, 0x8e, 0xc5, 0x98, 0x7b, 0xe9, 0xa5,
		0x6d, 0x66, 0xaf, 0x04, 0xc8, 0xb9, 0x7f, 0x12, 0x20, 0xc3, 0xc5, 0xd2, 0x29, 0x48, 0x39, 0x9a,
		0x7f, 0x40, 0xe8, 0xd2, 0x6b, 0x09, 0x51, 0x50, 0xc8, 0x33, 0x96, 0x7b, 0x8e, 0x66, 0x91, 0x14,
		0x60, 0x72, 0xfc, 0x8c, 0xe7, 0xd5, 0x44, 0x5a, 0x93, 0x1c, 0x3f, 0xec, 0x4e, 0x07, 0x59, 0xbe,
		0xc7, 0xe7, 0x95, 0xc9, 0xd7, 0x99, 0x58, 0x7a, 0x0e, 0xa6, 0x7d, 0x57, 0x33, 0xcc, 0x1e, 0xdb,
		0x14, 0xb1, 0x15, 0xb9, 0x22, 0x30, 0x2e, 0xc1, 0x19, 0xce, 0xdb, 0x44, 0xbe, 0xa6, 0x1f, 0xa0,
		0x66, 0x08, 0x1a, 0x27, 0x37, 0x98, 0xa7, 0x99, 0xc1, 0x06, 0xd3, 0x73, 0xec, 0xc2, 0x77, 0x05,
		0x98, 0xe6, 0x07, 0xa6, 0x66, 0x10, 0xac, 0x1d, 0x00, 0xcd, 0xb2, 0x6c, 0x3f, 0x1a, 0xae, 0xc1,
		0x54, 0x1e, 0xc0, 0x2d, 0x95, 0x03, 0x90, 0x12, 0x21, 0x98, 0xeb, 0x00, 0x84, 0x9a, 0x63, 0xc3,
		0x76, 0x16, 0x72, 0xec, 0x0b, 0x02, 0xf9, 0x0c, 0x45, 0x8f, 0xd8, 0x40, 0x45, 0xf8, 0x64, 0x25,
		0xcd, 0x42, 0xba, 0x81, 0xda, 0x86, 0xc5, 0xee, 0x35, 0xe9, 0x03, 0xbf, 0x2d, 0x4d, 0x05, 0xb7,
		0xa5, 0x6b, 0x37, 0x61, 0x46, 0xb7, 0x3b, 0xfd, 0xee, 0xae, 0x89, 0x7d, 0xc7, 0x7c, 0xef, 0xba,
		0xf0, 0x79, 0x08, 0x5b, 0xcc, 0x2f, 0x27, 0x92, 0x9b, 0xb5, 0xb5, 0xaf, 0x25, 0xe6, 0x36, 0x29,
		0xae, 0xc6, 0x87, 0xa9, 0xa0, 0x96, 0x89, 0x74, 0xec, 0x3a, 0xbc, 0xbb, 0x08, 0xcf, 0xb7, 0x0d,
		0xff, 0xa0, 0xdb, 0x58, 0xd2, 0xed, 0xce, 0xf2, 0x1d, 0xcd, 0x32, 0x0c, 0x53, 0x0b, 0xbf, 0xbc,
		0xb5, 0xed, 0xb6, 0x4d, 0x1e, 0xc8, 0x7f, 0xec, 0xeb, 0x5b, 0x36, 0x90, 0xce, 0xc5, 0x7e, 0xaa,
		0x2b, 0xed, 0xc2, 0x0c, 0x33, 0x56, 0xc9, 0xf5, 0x3f, 0x3d, 0x45, 0x48, 0x0f, 0xbd, 0x02, 0x92,
		0xbf, 0xf1, 0x01, 0x29, 0xd7, 0xca, 0x34, 0x83, 0x62, 0x1d, 0x3d, 0x68, 0x94, 0x14, 0x78, 0xa4,
		0x87, 0x8f, 0x2e, 0x4d, 0xe4, 0xc6, 0x30, 0x7e, 0x9b, 0x31, 0xce, 0x44, 0x18, 0xeb, 0x0c, 0x5a,
		0x5a, 0x87, 0xc9, 0x93, 0x70, 0xfd, 0x03, 0xe3, 0xca, 0xa3, 0x28, 0xc9, 0x26, 0x4c, 0x11, 0x12,
		0xbd, 0xeb, 0xf9, 0x76, 0x87, 0xec, 0x7b, 0x0f, 0xa7, 0xf9, 0xc7, 0x0f, 0xe8, 0x5a, 0x29, 0x60,
		0xd8, 0x7a, 0x80, 0x2a, 0x95, 0x80, 0x7c, 0xf1, 0x68, 0x22, 0xdd, 0x8c, 0x61, 0x78, 0x8f, 0x39,
		0x12, 0xd8, 0x97, 0x3e, 0x07, 0xb3, 0xf8, 0x7f, 0xb2, 0x2d, 0x45, 0x3d, 0x89, 0xbf, 0xf0, 0x92,
		0xbf, 0xfb, 0x3a, 0x5d, 0x8e, 0x33, 0x01, 0x41, 0xc4, 0xa7, 0xc8, 0x2c, 0xb6, 0x91, 0xef, 0x23,
		0xd7, 0x53, 0x35, 0x73, 0x98, 0x7b, 0x91, 0x1b, 0x03, 0xf9, 0x4b, 0x1f, 0xf6, 0xce, 0xe2, 0x26,
		0x45, 0x96, 0x4d, 0xb3, 0xb4, 0x0f, 0xa7, 0x87, 0x64, 0xc5, 0x08, 0x9c, 0x6f, 0x30, 0xce, 0xd9,
		0x81, 0xcc, 0xc0, 0xb4, 0x35, 0xe0, 0xf2, 0x60, 0x2e, 0x47, 0xe0, 0xfc, 0x3d, 0xc6, 0x29, 0x31,
		0x2c, 0x9f, 0x52, 0xcc, 0x78, 0x03, 0xa6, 0xef, 0x20, 0xb7, 0x61, 0x7b, 0xec, 0x96, 0x66, 0x04,
		0xba, 0x37, 0x19, 0xdd, 0x14, 0x03, 0x92, 0x6b, 0x1b, 0xcc, 0x75, 0x05, 0x32, 0x2d, 0x4d, 0x47,
		0x23, 0x50, 0xbc, 0xc5, 0x28, 0x26, 0xb0, 0x3d, 0x86, 0x96, 0x21, 0xdf, 0xb6, 0x59, 0x65, 0x8a,
		0x87, 0xbf, 0xcd, 0xe0, 0x39, 0x8e, 0x61, 0x14, 0x8e, 0xed, 0x74, 0x4d, 0x5c, 0xb6, 0xe2, 0x29,
		0x7e, 0x9f, 0x53, 0x70, 0x0c, 0xa3, 0x38, 0x41, 0x58, 0xff, 0x80, 0x53, 0x78, 0x91, 0x78, 0xbe,
		0x08, 0x39, 0xdb, 0x32, 0x0f, 0x6d, 0x6b, 0x14, 0x27, 0xfe, 0x90, 0x31, 0x00, 0x83, 0x60, 0x82,
		0xab, 0x90, 0x1d, 0x75, 0x22, 0xfe, 0xe8, 0x43, 0xbe, 0x3c, 0xf8, 0x0c, 0x6c, 0xc2, 0x14, 0xdf,
		0xa0, 0x0c, 0xdb, 0x1a, 0x81, 0xe2, 0x8f, 0x19, 0x45, 0x21, 0x02, 0x63, 0xc3, 0xf0, 0x91, 0xe7,
		0xb7, 0xd1, 0x28, 0x24, 0xef, 0xf0, 0x61, 0x30, 0x08, 0x0b, 0x65, 0x03, 0x59, 0xfa, 0xc1, 0x68,
		0x0c, 0x5f, 0xe1, 0xa1, 0xe4, 0x18, 0x4c, 0xb1, 0x0e, 0x93, 0x1d, 0xcd, 0xf5, 0x0e, 0x34, 0x73,
		0xa4, 0xe9, 0xf8, 0x2a, 0xe3, 0xc8, 0x07, 0x20, 0x16, 0x91, 0xae, 0x75, 0x12, 0x9a, 0xaf, 0xf1,
		0x88, 0x44, 0x60, 0x6c, 0xe9, 0x79, 0x3e, 0xb9, 0xd2, 0x3a, 0x09, 0xdb, 0x9f, 0xf0, 0xa5, 0x47,
		0xb1, 0x3b, 0x51, 0xc6, 0xab, 0x90, 0xf5, 0x8c, 0xd7, 0x46, 0xa2, 0xf9, 0x53, 0x3e, 0xd3, 0x04,
		0x80, 0xc1, 0x2f, 0xc3, 0x99, 0xa1, 0x65, 0x62, 0x04, 0xb2, 0x3f, 0x63, 0x64, 0xa7, 0x86, 0x94,
		0x0a, 0xb6, 0x25, 0x9c, 0x94, 0xf2, 0xcf, 0xf9, 0x96, 0x80, 0xfa, 0xb8, 0x6a, 0xf8, 0xac, 0xe0,
		0x69, 0xad, 0x93, 0x45, 0xed, 0x2f, 0x78, 0xd4, 0x28, 0xb6, 0x27, 0x6a, 0x7b, 0x70, 0x8a, 0x31,
		0x9e, 0x6c, 0x5e, 0xbf, 0xce, 0x37, 0x56, 0x8a, 0xde, 0xef, 0x9d, 0xdd, 0x9f, 0x83, 0xb9, 0x20,
		0x9c, 0xbc, 0x29, 0xf5, 0xd4, 0x8e, 0xe6, 0x8c, 0xc0, 0xfc, 0x0d, 0xc6, 0xcc, 0x77, 0xfc, 0xa0,
		0xab, 0xf5, 0x76, 0x34, 0x07, 0x93, 0xdf, 0x04, 0x99, 0x93, 0x77, 0x2d, 0x17, 0xe9, 0x76, 0xdb,
		0x32, 0x5e, 0x43, 0xcd, 0x11, 0xa8, 0xff, 0xb2, 0x6f, 0xaa, 0xf6, 0x23, 0x70, 0xcc, 0xbc, 0x05,
		0x62, 0xd0, 0xab, 0xa8, 0x46, 0xc7, 0xb1, 0x5d, 0x3f, 0x86, 0xf1, 0x5d, 0x3e, 0x53, 0x01, 0x6e,
		0x8b, 0xc0, 0x4a, 0x15, 0x28, 0x90, 0xc7, 0x51, 0x53, 0xf2, 0xaf, 0x18, 0xd1, 0x64, 0x88, 0x62,
		0x1b, 0x87, 0x6e, 0x77, 0x1c, 0xcd, 0x1d, 0x65, 0xff, 0xfb, 0x6b, 0xbe, 0x71, 0x30, 0x08, 0xdb,
		0x38, 0xfc, 0x43, 0x07, 0xe1, 0x6a, 0x3f, 0x02, 0xc3, 0x37, 0xf9, 0xc6, 0xc1, 0x31, 0x8c, 0x82,
		0x37, 0x0c, 0x23, 0x50, 0xfc, 0x0d, 0xa7, 0xe0, 0x18, 0x36, 0x8c, 0xb6, 0xab, 0x39, 0x07, 0xaf,
		0x8c, 0xc2, 0xf0, 0x2d, 0x3e, 0x0c, 0x06, 0xc1, 0x04, 0x9f, 0x0d, 0x2b, 0xb5, 0x8b, 0xda, 0x86,
		0xe7, 0xbb, 0xb4, 0x97, 0x7e, 0x38, 0xd3, 0xdf, 0x7e, 0xd8, 0xdb, 0xc5, 0x29, 0x11, 0x68, 0xe9,
		0x06, 0x4c, 0xf5, 0xf5, 0x28, 0x52, 0xdc, 0xef, 0x2f, 0xe4, 0x9f, 0x7f, 0xc0, 0x76, 0xb3, 0xde,
		0x16, 0xa5, 0xb4, 0x8d, 0x13, 0xa7, 0xb7, 0x91, 0x88, 0x27, 0x7b, 0xfd, 0x41, 0x90, 0x3b, 0x3d,
		0x7d, 0x44, 0xe9, 0x1a, 0x4c, 0xf6, 0x34, 0x11, 0xf1, 0x54, 0xbf, 0xc0, 0xa8, 0xf2, 0xd1, 0x1e,
		0xa2, 0xb4, 0x0a, 0x29, 0xdc, 0x10, 0xc4, 0xc3, 0x7f, 0x91, 0xc1, 0x89, 0x79, 0xe9, 0xd3, 0x90,
		0xe1, 0x8d, 0x40, 0x3c, 0xf4, 0x97, 0x18, 0x34, 0x80, 0x60, 0x38, 0x6f, 0x02, 0xe2, 0xe1, 0xbf,
		0xcc, 0xe1, 0x1c, 0x82, 0xe1, 0xa3, 0x87, 0xf0, 0xef, 0x7f, 0x25, 0xc5, 0x36, 0x72, 0x1e, 0xbb,
		0xab, 0x30, 0xc1, 0xaa, 0x7f, 0x3c, 0xfa, 0x0b, 0xec, 0xe5, 0x1c, 0x51, 0xba, 0x04, 0xe9, 0x11,
		0x03, 0xfe, 0xab, 0x0c, 0x4a, 0xed, 0x4b, 0xeb, 0x90, 0x8b, 0x54, 0xfc, 0x78, 0xf8, 0xaf, 0x31,
		0x78, 0x14, 0x85, 0x5d, 0x67, 0x15, 0x3f, 0x9e, 0xe0, 0xd7, 0xb9, 0xeb, 0x0c, 0x81, 0xc3, 0xc6,
		0x8b, 0x7d, 0x3c, 0xfa, 0x37, 0x78, 0xd4, 0x39, 0xa4, 0xf4, 0x22, 0x64, 0x83, 0x0d, 0x3c, 0x1e,
		0xff, 0x9b, 0x0c, 0x1f, 0x62, 0x70, 0x04, 0x22, 0x05, 0x24, 0x9e, 0xe2, 0xb7, 0x78, 0x04, 0x22,
		0x28, 0xbc, 0x8c, 0xfa, 0x9b, 0x82, 0x78, 0xa6, 0xdf, 0xe6, 0xcb, 0xa8, 0xaf, 0x27, 0xc0, 0xb3,
		0x49, 0xf6, 0xd1, 0x78, 0x8a, 0xdf, 0xe1, 0xb3, 0x49, 0xec, 0xb1, 0x1b, 0xfd, 0x55, 0x36, 0x9e,
		0xe3, 0x77, 0xb9, 0x1b, 0x7d, 0x45, 0xb6, 0x54, 0x03, 0x69, 0xb0, 0xc2, 0xc6, 0xf3, 0x7d, 0x91,
		0xf1, 0x4d, 0x0f, 0x14, 0xd8, 0xd2, 0x4b, 0x70, 0x6a, 0x78, 0x75, 0x8d, 0x67, 0xfd, 0xd2, 0x83,
		0xbe, 0xf3, 0x50, 0xb4, 0xb8, 0x96, 0xf6, 0xc2, 0x5d, 0x36, 0x5a, 0x59, 0xe3, 0x69, 0xdf, 0x78,
		0xd0, 0xbb, 0xd1, 0x46, 0x0b, 0x6b, 0xa9, 0x0c, 0x10, 0x16, 0xb5, 0x78, 0xae, 0x37, 0x19, 0x57,
		0x04, 0x84, 0x97, 0x06, 0xab, 0x69, 0xf1, 0xf8, 0xb7, 0xf8, 0xd2, 0x60, 0x08, 0xbc, 0x34, 0x78,
		0x39, 0x8b, 0x47, 0xbf, 0xcd, 0x97, 0x06, 0x87, 0x90, 0x95, 0x65, 0xf8, 0x2d, 0x53, 0x6b, 0x8f,
		0x50, 0x20, 0xbe, 0x1a, 0xac, 0x2c, 0x06, 0x29, 0x5d, 0x85, 0x8c, 0xd5, 0x35, 0x4d, 0x9c, 0x9a,
		0xd2, 0xc3, 0x7f, 0x51, 0x25, 0xff, 0xdb, 0xc7, 0x0c, 0xcc, 0x01, 0xa5, 0x55, 0x48, 0xa3, 0x4e,
		0x03, 0x35, 0xe3, 0x90, 0xff, 0xfe, 0x31, 0xdf, 0x8e, 0xb0, 0x75, 0xe9, 0x45, 0x00, 0x7a, 0x98,
		0x27, 0x1f, 0xaa, 0x62, 0xb0, 0x3f, 0xf8, 0x98, 0xfd, 0x58, 0x23, 0x84, 0x84, 0x04, 0xf4, 0xa7,
		0x1f, 0x0f, 0x27, 0xf8, 0xb0, 0x97, 0x80, 0x5c, 0x00, 0x5c, 0x81, 0x89, 0x5b, 0x9e, 0x6d, 0xf9,
		0x5a, 0x3b, 0x0e, 0xfd, 0x1f, 0x0c, 0xcd, 0xed, 0x71, 0xc0, 0x3a, 0xb6, 0x8b, 0x7c, 0x1c, 0xef,
		0x18, 0xec, 0x7f, 0x32, 0x6c, 0x00, 0xc0, 0x60, 0x5d, 0xf3, 0xfc, 0x51, 0xc6, 0xfd, 0x5f, 0x1c,
		0xcc, 0x01, 0xd8, 0x69, 0xfc, 0xff, 0x6d, 0x74, 0x18, 0x87, 0xfd, 0x88, 0x3b, 0xcd, 0xec, 0x4b,
		0x9f, 0x86, 0x2c, 0xfe, 0x97, 0xfe, 0x80, 0x29, 0x06, 0xfc, 0xdf, 0x0c, 0x1c, 0x22, 0xf0, 0x9b,
		0x3d, 0xbf, 0xe9, 0x1b, 0xf1, 0xc1, 0xfe, 0x1f, 0x36, 0xd3, 0xdc, 0xbe, 0x54, 0x86, 0x9c, 0xe7,
		0x37, 0x9b, 0x5d, 0xd6, 0x10, 0xc5, 0xc0, 0xff, 0xf7, 0xe3, 0xe0, 0x90, 0x1d, 0x60, 0x70, 0xd0,
		0x5c, 0xf4, 0x4a, 0xd7, 0x70, 0xe3, 0x13, 0xed, 0x01, 0x4f, 0x51, 0x0e, 0x58, 0x3b, 0x37, 0xfc,
		0xb2, 0x11, 0x36, 0xed, 0x4d, 0x9b, 0x5e, 0x33, 0xc2, 0x5b, 0x69, 0x78, 0x4c, 0xb7, 0x3b, 0x0d,
		0xdb, 0x5b, 0x8e, 0x6c, 0x81, 0xcb, 0xb6, 0xc5, 0xec, 0xa5, 0xa4, 0x6d, 0xa1, 0xb9, 0x13, 0x5f,
		0x2c, 0x2e, 0x9c, 0x81, 0x74, 0xbd, 0xdb, 0x68, 0x1c, 0x4a, 0x22, 0x24, 0xbd, 0x6e, 0x83, 0xfd,
		0x48, 0x07, 0xff, 0xbb, 0xf0, 0xbd, 0x24, 0xe4, 0xea, 0x5a, 0xc7, 0x31, 0x51, 0xd5, 0x42, 0xd5,
		0x96, 0x24, 0xc3, 0x38, 0x19, 0xc7, 0x0b, 0xc4, 0x48, 0xb8, 0x3e, 0xa6, 0xb0, 0xe7, 0x40, 0xb3,
		0x42, 0x2e, 0x5c, 0x13, 0x81, 0x66, 0x25, 0xd0, 0x9c, 0xa7, 0xf7, 0xad, 0x81, 0xe6, 0x7c, 0xa0,
		0xb9, 0x40, 0x6e, 0x5d, 0x93, 0x81, 0xe6, 0x42, 0xa0, 0x59, 0x25, 0x5f, 0x15, 0x26, 0x03, 0xcd,
		0x6a, 0xa0, 0xb9, 0x48, 0xbe, 0x23, 0xa4, 0x02, 0xcd, 0xc5, 0x40, 0x73, 0x89, 0x7c, 0x3e, 0x98,
		0x0e, 0x34, 0x97, 0x02, 0xcd, 0x65, 0xf2, 0xc9, 0x40, 0x0a, 0x34, 0x97, 0x03, 0xcd, 0x15, 0xf2,
		0x5b, 0x9c, 0x89, 0x40, 0x73, 0x45, 0x9a, 0x83, 0x09, 0x3a, 0xb2, 0xe7, 0xc9, 0x77, 0xe5, 0xa9,
		0xeb, 0x63, 0x0a, 0x17, 0x84, 0xba, 0x17, 0xc8, 0xef, 0x6d, 0xc6, 0x43, 0xdd, 0x0b, 0xa1, 0x6e,
		0x85, 0xfc, 0xea, 0x5c, 0x0c, 0x75, 0x2b, 0xa1, 0xee, 0xbc, 0x3c, 0x89, 0xa7, 0x3f, 0xd4, 0x9d,
		0x0f, 0x75, 0x17, 0xe4, 0x02, 0x8e, 0x7f, 0xa8, 0xbb, 0x10, 0xea, 0x56, 0xe5, 0xa9, 0x79, 0x61,
		0x31, 0x1f, 0xea, 0x56, 0xa5, 0x4f, 0x41, 0xce, 0xeb, 0x36, 0x54, 0xf6, 0x33, 0x08, 0xf2, 0xbb,
		0x9e, 0xdc, 0x0a, 0x2c, 0xe1, 0xa4, 0x20, 0x93, 0x7a, 0x7d, 0x4c, 0x01, 0xaf, 0xdb, 0x60, 0xfb,
		0xeb, 0x5a, 0x1e, 0xc8, 0x75, 0x88, 0x4a, 0x7e, 0xcd, 0xba, 0xb6, 0xf1, 0xde, 0xfd, 0xe2, 0xd8,
		0x77, 0xee, 0x17, 0xc7, 0xfe, 0xf9, 0x7e, 0x71, 0xec, 0xfd, 0xfb, 0x45, 0xe1, 0xa3, 0xfb, 0x45,
		0xe1, 0x87, 0xf7, 0x8b, 0xc2, 0xbd, 0xa3, 0xa2, 0xf0, 0x95, 0xa3, 0xa2, 0xf0, 0xf5, 0xa3, 0xa2,
		0xf0, 0xad, 0xa3, 0xa2, 0xf0, 0xde, 0x51, 0x71, 0xec, 0x3b, 0x47, 0x45, 0xe1, 0xfd, 0xa3, 0xa2,
		0xf0, 0xfd, 0xa3, 0xe2, 0xd8, 0x47, 0x47, 0x45, 0xe1, 0x87, 0x47, 0xc5, 0xb1, 0x7b, 0xff, 0x52,
		0x1c, 0x6b, 0x8c, 0x93, 0x34, 0x3a, 0xff, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff, 0xe0, 0xc1, 0xe8,
		0xc6, 0x44, 0x32, 0x00, 0x00,
	}
	r := bytes.NewReader(gzipped)
	gzipr, err := compress_gzip.NewReader(r)
	if err != nil {
		panic(err)
	}
	ungzipped, err := io_ioutil.ReadAll(gzipr)
	if err != nil {
		panic(err)
	}
	if err := github_com_vaniila_protobuf_proto.Unmarshal(ungzipped, d); err != nil {
		panic(err)
	}
	return d
}
func (this *Subby) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *Subby")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *Subby but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *Subby but is not nil && this == nil")
	}
	if this.Sub != that1.Sub {
		return fmt.Errorf("Sub this(%v) Not Equal that(%v)", this.Sub, that1.Sub)
	}
	return nil
}
func (this *Subby) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*Subby)
	if !ok {
		that2, ok := that.(Subby)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Sub != that1.Sub {
		return false
	}
	return true
}
func (this *SampleOneOf) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf but is not nil && this == nil")
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return fmt.Errorf("this.TestOneof != nil && that1.TestOneof == nil")
		}
	} else if this.TestOneof == nil {
		return fmt.Errorf("this.TestOneof == nil && that1.TestOneof != nil")
	} else if err := this.TestOneof.VerboseEqual(that1.TestOneof); err != nil {
		return err
	}
	return nil
}
func (this *SampleOneOf_Field1) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field1")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field1 but is not nil && this == nil")
	}
	if this.Field1 != that1.Field1 {
		return fmt.Errorf("Field1 this(%v) Not Equal that(%v)", this.Field1, that1.Field1)
	}
	return nil
}
func (this *SampleOneOf_Field2) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field2")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field2 but is not nil && this == nil")
	}
	if this.Field2 != that1.Field2 {
		return fmt.Errorf("Field2 this(%v) Not Equal that(%v)", this.Field2, that1.Field2)
	}
	return nil
}
func (this *SampleOneOf_Field3) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field3")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field3 but is not nil && this == nil")
	}
	if this.Field3 != that1.Field3 {
		return fmt.Errorf("Field3 this(%v) Not Equal that(%v)", this.Field3, that1.Field3)
	}
	return nil
}
func (this *SampleOneOf_Field4) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field4")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field4 but is not nil && this == nil")
	}
	if this.Field4 != that1.Field4 {
		return fmt.Errorf("Field4 this(%v) Not Equal that(%v)", this.Field4, that1.Field4)
	}
	return nil
}
func (this *SampleOneOf_Field5) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field5")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field5 but is not nil && this == nil")
	}
	if this.Field5 != that1.Field5 {
		return fmt.Errorf("Field5 this(%v) Not Equal that(%v)", this.Field5, that1.Field5)
	}
	return nil
}
func (this *SampleOneOf_Field6) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field6")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field6 but is not nil && this == nil")
	}
	if this.Field6 != that1.Field6 {
		return fmt.Errorf("Field6 this(%v) Not Equal that(%v)", this.Field6, that1.Field6)
	}
	return nil
}
func (this *SampleOneOf_Field7) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field7")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field7 but is not nil && this == nil")
	}
	if this.Field7 != that1.Field7 {
		return fmt.Errorf("Field7 this(%v) Not Equal that(%v)", this.Field7, that1.Field7)
	}
	return nil
}
func (this *SampleOneOf_Field8) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field8")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field8 but is not nil && this == nil")
	}
	if this.Field8 != that1.Field8 {
		return fmt.Errorf("Field8 this(%v) Not Equal that(%v)", this.Field8, that1.Field8)
	}
	return nil
}
func (this *SampleOneOf_Field9) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field9")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field9 but is not nil && this == nil")
	}
	if this.Field9 != that1.Field9 {
		return fmt.Errorf("Field9 this(%v) Not Equal that(%v)", this.Field9, that1.Field9)
	}
	return nil
}
func (this *SampleOneOf_Field10) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field10")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field10 but is not nil && this == nil")
	}
	if this.Field10 != that1.Field10 {
		return fmt.Errorf("Field10 this(%v) Not Equal that(%v)", this.Field10, that1.Field10)
	}
	return nil
}
func (this *SampleOneOf_Field11) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field11")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field11 but is not nil && this == nil")
	}
	if this.Field11 != that1.Field11 {
		return fmt.Errorf("Field11 this(%v) Not Equal that(%v)", this.Field11, that1.Field11)
	}
	return nil
}
func (this *SampleOneOf_Field12) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field12")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field12 but is not nil && this == nil")
	}
	if this.Field12 != that1.Field12 {
		return fmt.Errorf("Field12 this(%v) Not Equal that(%v)", this.Field12, that1.Field12)
	}
	return nil
}
func (this *SampleOneOf_Field13) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field13")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field13 but is not nil && this == nil")
	}
	if this.Field13 != that1.Field13 {
		return fmt.Errorf("Field13 this(%v) Not Equal that(%v)", this.Field13, that1.Field13)
	}
	return nil
}
func (this *SampleOneOf_Field14) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field14")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field14 but is not nil && this == nil")
	}
	if this.Field14 != that1.Field14 {
		return fmt.Errorf("Field14 this(%v) Not Equal that(%v)", this.Field14, that1.Field14)
	}
	return nil
}
func (this *SampleOneOf_Field15) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_Field15")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_Field15 but is not nil && this == nil")
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return fmt.Errorf("Field15 this(%v) Not Equal that(%v)", this.Field15, that1.Field15)
	}
	return nil
}
func (this *SampleOneOf_SubMessage) VerboseEqual(that interface{}) error {
	if that == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that == nil && this != nil")
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return fmt.Errorf("that is not of type *SampleOneOf_SubMessage")
		}
	}
	if that1 == nil {
		if this == nil {
			return nil
		}
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is nil && this != nil")
	} else if this == nil {
		return fmt.Errorf("that is type *SampleOneOf_SubMessage but is not nil && this == nil")
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return fmt.Errorf("SubMessage this(%v) Not Equal that(%v)", this.SubMessage, that1.SubMessage)
	}
	return nil
}
func (this *SampleOneOf) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf)
	if !ok {
		that2, ok := that.(SampleOneOf)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if that1.TestOneof == nil {
		if this.TestOneof != nil {
			return false
		}
	} else if this.TestOneof == nil {
		return false
	} else if !this.TestOneof.Equal(that1.TestOneof) {
		return false
	}
	return true
}
func (this *SampleOneOf_Field1) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field1)
	if !ok {
		that2, ok := that.(SampleOneOf_Field1)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field1 != that1.Field1 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field2) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field2)
	if !ok {
		that2, ok := that.(SampleOneOf_Field2)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field2 != that1.Field2 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field3) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field3)
	if !ok {
		that2, ok := that.(SampleOneOf_Field3)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field3 != that1.Field3 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field4) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field4)
	if !ok {
		that2, ok := that.(SampleOneOf_Field4)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field4 != that1.Field4 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field5) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field5)
	if !ok {
		that2, ok := that.(SampleOneOf_Field5)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field5 != that1.Field5 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field6) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field6)
	if !ok {
		that2, ok := that.(SampleOneOf_Field6)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field6 != that1.Field6 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field7) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field7)
	if !ok {
		that2, ok := that.(SampleOneOf_Field7)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field7 != that1.Field7 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field8) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field8)
	if !ok {
		that2, ok := that.(SampleOneOf_Field8)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field8 != that1.Field8 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field9) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field9)
	if !ok {
		that2, ok := that.(SampleOneOf_Field9)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field9 != that1.Field9 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field10) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field10)
	if !ok {
		that2, ok := that.(SampleOneOf_Field10)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field10 != that1.Field10 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field11) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field11)
	if !ok {
		that2, ok := that.(SampleOneOf_Field11)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field11 != that1.Field11 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field12) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field12)
	if !ok {
		that2, ok := that.(SampleOneOf_Field12)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field12 != that1.Field12 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field13) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field13)
	if !ok {
		that2, ok := that.(SampleOneOf_Field13)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field13 != that1.Field13 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field14) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field14)
	if !ok {
		that2, ok := that.(SampleOneOf_Field14)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if this.Field14 != that1.Field14 {
		return false
	}
	return true
}
func (this *SampleOneOf_Field15) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_Field15)
	if !ok {
		that2, ok := that.(SampleOneOf_Field15)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !bytes.Equal(this.Field15, that1.Field15) {
		return false
	}
	return true
}
func (this *SampleOneOf_SubMessage) Equal(that interface{}) bool {
	if that == nil {
		if this == nil {
			return true
		}
		return false
	}

	that1, ok := that.(*SampleOneOf_SubMessage)
	if !ok {
		that2, ok := that.(SampleOneOf_SubMessage)
		if ok {
			that1 = &that2
		} else {
			return false
		}
	}
	if that1 == nil {
		if this == nil {
			return true
		}
		return false
	} else if this == nil {
		return false
	}
	if !this.SubMessage.Equal(that1.SubMessage) {
		return false
	}
	return true
}
func (this *Subby) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 5)
	s = append(s, "&one.Subby{")
	s = append(s, "Sub: "+fmt.Sprintf("%#v", this.Sub)+",\n")
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf) GoString() string {
	if this == nil {
		return "nil"
	}
	s := make([]string, 0, 20)
	s = append(s, "&one.SampleOneOf{")
	if this.TestOneof != nil {
		s = append(s, "TestOneof: "+fmt.Sprintf("%#v", this.TestOneof)+",\n")
	}
	s = append(s, "}")
	return strings.Join(s, "")
}
func (this *SampleOneOf_Field1) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field1{` +
		`Field1:` + fmt.Sprintf("%#v", this.Field1) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field2) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field2{` +
		`Field2:` + fmt.Sprintf("%#v", this.Field2) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field3) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field3{` +
		`Field3:` + fmt.Sprintf("%#v", this.Field3) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field4) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field4{` +
		`Field4:` + fmt.Sprintf("%#v", this.Field4) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field5) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field5{` +
		`Field5:` + fmt.Sprintf("%#v", this.Field5) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field6) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field6{` +
		`Field6:` + fmt.Sprintf("%#v", this.Field6) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field7) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field7{` +
		`Field7:` + fmt.Sprintf("%#v", this.Field7) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field8) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field8{` +
		`Field8:` + fmt.Sprintf("%#v", this.Field8) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field9) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field9{` +
		`Field9:` + fmt.Sprintf("%#v", this.Field9) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field10) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field10{` +
		`Field10:` + fmt.Sprintf("%#v", this.Field10) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field11) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field11{` +
		`Field11:` + fmt.Sprintf("%#v", this.Field11) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field12) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field12{` +
		`Field12:` + fmt.Sprintf("%#v", this.Field12) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field13) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field13{` +
		`Field13:` + fmt.Sprintf("%#v", this.Field13) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field14) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field14{` +
		`Field14:` + fmt.Sprintf("%#v", this.Field14) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_Field15) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_Field15{` +
		`Field15:` + fmt.Sprintf("%#v", this.Field15) + `}`}, ", ")
	return s
}
func (this *SampleOneOf_SubMessage) GoString() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&one.SampleOneOf_SubMessage{` +
		`SubMessage:` + fmt.Sprintf("%#v", this.SubMessage) + `}`}, ", ")
	return s
}
func valueToGoStringOne(v interface{}, typ string) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("func(v %v) *%v { return &v } ( %#v )", typ, typ, pv)
}
func NewPopulatedSubby(r randyOne, easy bool) *Subby {
	this := &Subby{}
	this.Sub = string(randStringOne(r))
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSampleOneOf(r randyOne, easy bool) *SampleOneOf {
	this := &SampleOneOf{}
	oneofNumber_TestOneof := []int32{1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16}[r.Intn(16)]
	switch oneofNumber_TestOneof {
	case 1:
		this.TestOneof = NewPopulatedSampleOneOf_Field1(r, easy)
	case 2:
		this.TestOneof = NewPopulatedSampleOneOf_Field2(r, easy)
	case 3:
		this.TestOneof = NewPopulatedSampleOneOf_Field3(r, easy)
	case 4:
		this.TestOneof = NewPopulatedSampleOneOf_Field4(r, easy)
	case 5:
		this.TestOneof = NewPopulatedSampleOneOf_Field5(r, easy)
	case 6:
		this.TestOneof = NewPopulatedSampleOneOf_Field6(r, easy)
	case 7:
		this.TestOneof = NewPopulatedSampleOneOf_Field7(r, easy)
	case 8:
		this.TestOneof = NewPopulatedSampleOneOf_Field8(r, easy)
	case 9:
		this.TestOneof = NewPopulatedSampleOneOf_Field9(r, easy)
	case 10:
		this.TestOneof = NewPopulatedSampleOneOf_Field10(r, easy)
	case 11:
		this.TestOneof = NewPopulatedSampleOneOf_Field11(r, easy)
	case 12:
		this.TestOneof = NewPopulatedSampleOneOf_Field12(r, easy)
	case 13:
		this.TestOneof = NewPopulatedSampleOneOf_Field13(r, easy)
	case 14:
		this.TestOneof = NewPopulatedSampleOneOf_Field14(r, easy)
	case 15:
		this.TestOneof = NewPopulatedSampleOneOf_Field15(r, easy)
	case 16:
		this.TestOneof = NewPopulatedSampleOneOf_SubMessage(r, easy)
	}
	if !easy && r.Intn(10) != 0 {
	}
	return this
}

func NewPopulatedSampleOneOf_Field1(r randyOne, easy bool) *SampleOneOf_Field1 {
	this := &SampleOneOf_Field1{}
	this.Field1 = float64(r.Float64())
	if r.Intn(2) == 0 {
		this.Field1 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field2(r randyOne, easy bool) *SampleOneOf_Field2 {
	this := &SampleOneOf_Field2{}
	this.Field2 = float32(r.Float32())
	if r.Intn(2) == 0 {
		this.Field2 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field3(r randyOne, easy bool) *SampleOneOf_Field3 {
	this := &SampleOneOf_Field3{}
	this.Field3 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field3 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field4(r randyOne, easy bool) *SampleOneOf_Field4 {
	this := &SampleOneOf_Field4{}
	this.Field4 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field4 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field5(r randyOne, easy bool) *SampleOneOf_Field5 {
	this := &SampleOneOf_Field5{}
	this.Field5 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field6(r randyOne, easy bool) *SampleOneOf_Field6 {
	this := &SampleOneOf_Field6{}
	this.Field6 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field7(r randyOne, easy bool) *SampleOneOf_Field7 {
	this := &SampleOneOf_Field7{}
	this.Field7 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field7 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field8(r randyOne, easy bool) *SampleOneOf_Field8 {
	this := &SampleOneOf_Field8{}
	this.Field8 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field8 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field9(r randyOne, easy bool) *SampleOneOf_Field9 {
	this := &SampleOneOf_Field9{}
	this.Field9 = uint32(r.Uint32())
	return this
}
func NewPopulatedSampleOneOf_Field10(r randyOne, easy bool) *SampleOneOf_Field10 {
	this := &SampleOneOf_Field10{}
	this.Field10 = int32(r.Int31())
	if r.Intn(2) == 0 {
		this.Field10 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field11(r randyOne, easy bool) *SampleOneOf_Field11 {
	this := &SampleOneOf_Field11{}
	this.Field11 = uint64(uint64(r.Uint32()))
	return this
}
func NewPopulatedSampleOneOf_Field12(r randyOne, easy bool) *SampleOneOf_Field12 {
	this := &SampleOneOf_Field12{}
	this.Field12 = int64(r.Int63())
	if r.Intn(2) == 0 {
		this.Field12 *= -1
	}
	return this
}
func NewPopulatedSampleOneOf_Field13(r randyOne, easy bool) *SampleOneOf_Field13 {
	this := &SampleOneOf_Field13{}
	this.Field13 = bool(bool(r.Intn(2) == 0))
	return this
}
func NewPopulatedSampleOneOf_Field14(r randyOne, easy bool) *SampleOneOf_Field14 {
	this := &SampleOneOf_Field14{}
	this.Field14 = string(randStringOne(r))
	return this
}
func NewPopulatedSampleOneOf_Field15(r randyOne, easy bool) *SampleOneOf_Field15 {
	this := &SampleOneOf_Field15{}
	v1 := r.Intn(100)
	this.Field15 = make([]byte, v1)
	for i := 0; i < v1; i++ {
		this.Field15[i] = byte(r.Intn(256))
	}
	return this
}
func NewPopulatedSampleOneOf_SubMessage(r randyOne, easy bool) *SampleOneOf_SubMessage {
	this := &SampleOneOf_SubMessage{}
	this.SubMessage = NewPopulatedSubby(r, easy)
	return this
}

type randyOne interface {
	Float32() float32
	Float64() float64
	Int63() int64
	Int31() int32
	Uint32() uint32
	Intn(n int) int
}

func randUTF8RuneOne(r randyOne) rune {
	ru := r.Intn(62)
	if ru < 10 {
		return rune(ru + 48)
	} else if ru < 36 {
		return rune(ru + 55)
	}
	return rune(ru + 61)
}
func randStringOne(r randyOne) string {
	v2 := r.Intn(100)
	tmps := make([]rune, v2)
	for i := 0; i < v2; i++ {
		tmps[i] = randUTF8RuneOne(r)
	}
	return string(tmps)
}
func randUnrecognizedOne(r randyOne, maxFieldNumber int) (dAtA []byte) {
	l := r.Intn(5)
	for i := 0; i < l; i++ {
		wire := r.Intn(4)
		if wire == 3 {
			wire = 5
		}
		fieldNumber := maxFieldNumber + r.Intn(100)
		dAtA = randFieldOne(dAtA, r, fieldNumber, wire)
	}
	return dAtA
}
func randFieldOne(dAtA []byte, r randyOne, fieldNumber int, wire int) []byte {
	key := uint32(fieldNumber)<<3 | uint32(wire)
	switch wire {
	case 0:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		v3 := r.Int63()
		if r.Intn(2) == 0 {
			v3 *= -1
		}
		dAtA = encodeVarintPopulateOne(dAtA, uint64(v3))
	case 1:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	case 2:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		ll := r.Intn(100)
		dAtA = encodeVarintPopulateOne(dAtA, uint64(ll))
		for j := 0; j < ll; j++ {
			dAtA = append(dAtA, byte(r.Intn(256)))
		}
	default:
		dAtA = encodeVarintPopulateOne(dAtA, uint64(key))
		dAtA = append(dAtA, byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)), byte(r.Intn(256)))
	}
	return dAtA
}
func encodeVarintPopulateOne(dAtA []byte, v uint64) []byte {
	for v >= 1<<7 {
		dAtA = append(dAtA, uint8(uint64(v)&0x7f|0x80))
		v >>= 7
	}
	dAtA = append(dAtA, uint8(v))
	return dAtA
}
func (m *Subby) Size() (n int) {
	var l int
	_ = l
	l = len(m.Sub)
	if l > 0 {
		n += 1 + l + sovOne(uint64(l))
	}
	return n
}

func (m *SampleOneOf) Size() (n int) {
	var l int
	_ = l
	if m.TestOneof != nil {
		n += m.TestOneof.Size()
	}
	return n
}

func (m *SampleOneOf_Field1) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field2) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field3) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field3))
	return n
}
func (m *SampleOneOf_Field4) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field4))
	return n
}
func (m *SampleOneOf_Field5) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field5))
	return n
}
func (m *SampleOneOf_Field6) Size() (n int) {
	var l int
	_ = l
	n += 1 + sovOne(uint64(m.Field6))
	return n
}
func (m *SampleOneOf_Field7) Size() (n int) {
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field7))
	return n
}
func (m *SampleOneOf_Field8) Size() (n int) {
	var l int
	_ = l
	n += 1 + sozOne(uint64(m.Field8))
	return n
}
func (m *SampleOneOf_Field9) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field10) Size() (n int) {
	var l int
	_ = l
	n += 5
	return n
}
func (m *SampleOneOf_Field11) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field12) Size() (n int) {
	var l int
	_ = l
	n += 9
	return n
}
func (m *SampleOneOf_Field13) Size() (n int) {
	var l int
	_ = l
	n += 2
	return n
}
func (m *SampleOneOf_Field14) Size() (n int) {
	var l int
	_ = l
	l = len(m.Field14)
	n += 1 + l + sovOne(uint64(l))
	return n
}
func (m *SampleOneOf_Field15) Size() (n int) {
	var l int
	_ = l
	if m.Field15 != nil {
		l = len(m.Field15)
		n += 1 + l + sovOne(uint64(l))
	}
	return n
}
func (m *SampleOneOf_SubMessage) Size() (n int) {
	var l int
	_ = l
	if m.SubMessage != nil {
		l = m.SubMessage.Size()
		n += 2 + l + sovOne(uint64(l))
	}
	return n
}

func sovOne(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozOne(x uint64) (n int) {
	return sovOne(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Subby) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Subby{`,
		`Sub:` + fmt.Sprintf("%v", this.Sub) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf{`,
		`TestOneof:` + fmt.Sprintf("%v", this.TestOneof) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field1) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field1{`,
		`Field1:` + fmt.Sprintf("%v", this.Field1) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field2) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field2{`,
		`Field2:` + fmt.Sprintf("%v", this.Field2) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field3) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field3{`,
		`Field3:` + fmt.Sprintf("%v", this.Field3) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field4) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field4{`,
		`Field4:` + fmt.Sprintf("%v", this.Field4) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field5) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field5{`,
		`Field5:` + fmt.Sprintf("%v", this.Field5) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field6) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field6{`,
		`Field6:` + fmt.Sprintf("%v", this.Field6) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field7) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field7{`,
		`Field7:` + fmt.Sprintf("%v", this.Field7) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field8) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field8{`,
		`Field8:` + fmt.Sprintf("%v", this.Field8) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field9) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field9{`,
		`Field9:` + fmt.Sprintf("%v", this.Field9) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field10) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field10{`,
		`Field10:` + fmt.Sprintf("%v", this.Field10) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field11) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field11{`,
		`Field11:` + fmt.Sprintf("%v", this.Field11) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field12) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field12{`,
		`Field12:` + fmt.Sprintf("%v", this.Field12) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field13) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field13{`,
		`Field13:` + fmt.Sprintf("%v", this.Field13) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field14) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field14{`,
		`Field14:` + fmt.Sprintf("%v", this.Field14) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_Field15) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_Field15{`,
		`Field15:` + fmt.Sprintf("%v", this.Field15) + `,`,
		`}`,
	}, "")
	return s
}
func (this *SampleOneOf_SubMessage) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&SampleOneOf_SubMessage{`,
		`SubMessage:` + strings.Replace(fmt.Sprintf("%v", this.SubMessage), "Subby", "Subby", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringOne(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Subby) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOne
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Subby: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Subby: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Sub", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOne
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Sub = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOne(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOne
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SampleOneOf) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowOne
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SampleOneOf: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SampleOneOf: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field1", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.TestOneof = &SampleOneOf_Field1{float64(math.Float64frombits(v))}
		case 2:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field2", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.TestOneof = &SampleOneOf_Field2{float32(math.Float32frombits(v))}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field3", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestOneof = &SampleOneOf_Field3{v}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field4", wireType)
			}
			var v int64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestOneof = &SampleOneOf_Field4{v}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field5", wireType)
			}
			var v uint32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestOneof = &SampleOneOf_Field5{v}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field6", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.TestOneof = &SampleOneOf_Field6{v}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field7", wireType)
			}
			var v int32
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int32(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = int32((uint32(v) >> 1) ^ uint32(((v&1)<<31)>>31))
			m.TestOneof = &SampleOneOf_Field7{v}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field8", wireType)
			}
			var v uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			v = (v >> 1) ^ uint64((int64(v&1)<<63)>>63)
			m.TestOneof = &SampleOneOf_Field8{int64(v)}
		case 9:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field9", wireType)
			}
			var v uint32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = uint32(dAtA[iNdEx-4])
			v |= uint32(dAtA[iNdEx-3]) << 8
			v |= uint32(dAtA[iNdEx-2]) << 16
			v |= uint32(dAtA[iNdEx-1]) << 24
			m.TestOneof = &SampleOneOf_Field9{v}
		case 10:
			if wireType != 5 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field10", wireType)
			}
			var v int32
			if (iNdEx + 4) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 4
			v = int32(dAtA[iNdEx-4])
			v |= int32(dAtA[iNdEx-3]) << 8
			v |= int32(dAtA[iNdEx-2]) << 16
			v |= int32(dAtA[iNdEx-1]) << 24
			m.TestOneof = &SampleOneOf_Field10{v}
		case 11:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field11", wireType)
			}
			var v uint64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = uint64(dAtA[iNdEx-8])
			v |= uint64(dAtA[iNdEx-7]) << 8
			v |= uint64(dAtA[iNdEx-6]) << 16
			v |= uint64(dAtA[iNdEx-5]) << 24
			v |= uint64(dAtA[iNdEx-4]) << 32
			v |= uint64(dAtA[iNdEx-3]) << 40
			v |= uint64(dAtA[iNdEx-2]) << 48
			v |= uint64(dAtA[iNdEx-1]) << 56
			m.TestOneof = &SampleOneOf_Field11{v}
		case 12:
			if wireType != 1 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field12", wireType)
			}
			var v int64
			if (iNdEx + 8) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += 8
			v = int64(dAtA[iNdEx-8])
			v |= int64(dAtA[iNdEx-7]) << 8
			v |= int64(dAtA[iNdEx-6]) << 16
			v |= int64(dAtA[iNdEx-5]) << 24
			v |= int64(dAtA[iNdEx-4]) << 32
			v |= int64(dAtA[iNdEx-3]) << 40
			v |= int64(dAtA[iNdEx-2]) << 48
			v |= int64(dAtA[iNdEx-1]) << 56
			m.TestOneof = &SampleOneOf_Field12{v}
		case 13:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field13", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			b := bool(v != 0)
			m.TestOneof = &SampleOneOf_Field13{b}
		case 14:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field14", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthOne
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TestOneof = &SampleOneOf_Field14{string(dAtA[iNdEx:postIndex])}
			iNdEx = postIndex
		case 15:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Field15", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthOne
			}
			postIndex := iNdEx + byteLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := make([]byte, postIndex-iNdEx)
			copy(v, dAtA[iNdEx:postIndex])
			m.TestOneof = &SampleOneOf_Field15{v}
			iNdEx = postIndex
		case 16:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SubMessage", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowOne
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthOne
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			v := &Subby{}
			if err := v.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			m.TestOneof = &SampleOneOf_SubMessage{v}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipOne(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthOne
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipOne(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowOne
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOne
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowOne
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthOne
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowOne
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipOne(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthOne = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowOne   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("combos/unmarshaler/one.proto", fileDescriptorOne) }

var fileDescriptorOne = []byte{
	// 415 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x44, 0xd2, 0xbf, 0x6e, 0xdb, 0x30,
	0x10, 0x06, 0x70, 0x5e, 0x14, 0xdb, 0x09, 0xed, 0x34, 0xae, 0xa6, 0x6b, 0x50, 0x1c, 0x88, 0x4c,
	0x5c, 0x6a, 0xc5, 0x92, 0x9d, 0x3f, 0x6b, 0x50, 0x14, 0x5e, 0x8a, 0x00, 0xce, 0x03, 0x04, 0x62,
	0x4a, 0x3b, 0x06, 0x2c, 0x31, 0xb0, 0xa4, 0x02, 0xdd, 0xf2, 0x38, 0x1d, 0x3b, 0xf6, 0x11, 0x32,
	0x66, 0xec, 0xd0, 0x21, 0x62, 0x97, 0x8e, 0x19, 0x3d, 0x16, 0x96, 0x1b, 0x72, 0xbb, 0x8f, 0x3f,
	0x72, 0x20, 0xf9, 0xf1, 0xf7, 0xb7, 0x26, 0x53, 0xa6, 0x88, 0xaa, 0x3c, 0x4b, 0x57, 0xc5, 0x5d,
	0xba, 0xd4, 0xab, 0xc8, 0xe4, 0x7a, 0x70, 0xbf, 0x32, 0xa5, 0x09, 0x03, 0x93, 0xeb, 0xa3, 0x93,
	0xf9, 0xa2, 0xbc, 0xab, 0xd4, 0xe0, 0xd6, 0x64, 0xd1, 0xd7, 0x34, 0x5f, 0x2c, 0x96, 0x69, 0xd4,
	0xb0, 0xaa, 0x66, 0xd1, 0xdc, 0xcc, 0x4d, 0x13, 0x9a, 0x69, 0x7b, 0xec, 0xf8, 0x1d, 0x6f, 0x5d,
	0x57, 0x4a, 0x7d, 0x0b, 0xfb, 0x3c, 0x28, 0x2a, 0x85, 0x20, 0x40, 0xee, 0x4f, 0x37, 0xe3, 0xf1,
	0xef, 0x80, 0x77, 0xaf, 0xd3, 0xec, 0x7e, 0xa9, 0xaf, 0x72, 0x7d, 0x35, 0x0b, 0x91, 0xb7, 0x3f,
	0x2d, 0xf4, 0xf2, 0xcb, 0xb0, 0xd9, 0x04, 0x13, 0x36, 0xfd, 0x9f, 0x9d, 0xc4, 0xb8, 0x23, 0x40,
	0xee, 0x38, 0x89, 0x9d, 0x24, 0x18, 0x08, 0x90, 0x2d, 0x27, 0x89, 0x93, 0x11, 0xee, 0x0a, 0x90,
	0x81, 0x93, 0x91, 0x93, 0x31, 0xb6, 0x04, 0xc8, 0x03, 0x27, 0x63, 0x27, 0xa7, 0xd8, 0x16, 0x20,
	0x77, 0x9d, 0x9c, 0x3a, 0x39, 0xc3, 0x8e, 0x00, 0xf9, 0xd6, 0xc9, 0x99, 0x93, 0x73, 0xdc, 0x13,
	0x20, 0x43, 0x27, 0xe7, 0x4e, 0x2e, 0x70, 0x5f, 0x80, 0xec, 0x38, 0xb9, 0x08, 0x8f, 0x78, 0x67,
	0x7b, 0xb3, 0x13, 0xe4, 0x02, 0xe4, 0xe1, 0x84, 0x4d, 0x5f, 0x17, 0xbc, 0x0d, 0xb1, 0x2b, 0x40,
	0xb6, 0xbd, 0x0d, 0xbd, 0xc5, 0xd8, 0x13, 0x20, 0xfb, 0xde, 0x62, 0x6f, 0x09, 0x1e, 0x08, 0x90,
	0x7b, 0xde, 0x12, 0x6f, 0x23, 0x7c, 0xb3, 0x79, 0x7f, 0x6f, 0x23, 0x6f, 0x63, 0x3c, 0x14, 0x20,
	0x7b, 0xde, 0xc6, 0xe1, 0x07, 0xde, 0x2d, 0x2a, 0x75, 0x93, 0xe9, 0xa2, 0x48, 0xe7, 0x1a, 0xfb,
	0x02, 0x64, 0x37, 0xe6, 0x83, 0x4d, 0x29, 0x9a, 0x4f, 0x9d, 0xb0, 0x29, 0x2f, 0x2a, 0xf5, 0x79,
	0xeb, 0x97, 0x3d, 0xce, 0x4b, 0x5d, 0x94, 0x37, 0x26, 0xd7, 0x66, 0x76, 0xf9, 0xf1, 0xb1, 0x26,
	0xf6, 0x54, 0x13, 0xfb, 0x55, 0x13, 0x7b, 0xae, 0x09, 0x5e, 0x6a, 0x82, 0x75, 0x4d, 0xf0, 0x60,
	0x09, 0xbe, 0x5b, 0x82, 0x1f, 0x96, 0xe0, 0xa7, 0x25, 0x78, 0xb4, 0xc4, 0x9e, 0x2c, 0xc1, 0xb3,
	0x25, 0xf8, 0x6b, 0x89, 0xbd, 0x58, 0x82, 0xb5, 0x25, 0xf6, 0xf0, 0x87, 0x98, 0x6a, 0x37, 0x35,
	0x4a, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x7e, 0x52, 0x03, 0xe2, 0x9d, 0x02, 0x00, 0x00,
}
