// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: internal.proto

/*
	Package internal is a generated protocol buffer package.

	It is generated from these files:
		internal.proto

	It has these top-level messages:
		Error
		ExtendedRequest
		ExtendedResponse
*/
package internal

import proto "github.com/vaniila/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/vaniila/protobuf/gogoproto"

import strings "strings"
import reflect "reflect"
import github_com_vaniila_protobuf_sortkeys "github.com/vaniila/protobuf/sortkeys"

import io "io"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type ErrorType int32

const (
	Unknown ErrorType = 0
	System  ErrorType = 1
	Client  ErrorType = 2
)

var ErrorType_name = map[int32]string{
	0: "Unknown",
	1: "System",
	2: "Client",
}
var ErrorType_value = map[string]int32{
	"Unknown": 0,
	"System":  1,
	"Client":  2,
}

func (x ErrorType) String() string {
	return proto.EnumName(ErrorType_name, int32(x))
}
func (ErrorType) EnumDescriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

type Error struct {
	Cause string    `protobuf:"bytes,1,opt,name=cause,proto3" json:"cause,omitempty"`
	Type  ErrorType `protobuf:"varint,2,opt,name=type,proto3,enum=internal.ErrorType" json:"type,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{0} }

func (m *Error) GetCause() string {
	if m != nil {
		return m.Cause
	}
	return ""
}

func (m *Error) GetType() ErrorType {
	if m != nil {
		return m.Type
	}
	return Unknown
}

type ExtendedRequest struct {
	RequestMetadata   map[string]string `protobuf:"bytes,1,rep,name=request_metadata,json=requestMetadata" json:"request_metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	OptionErrorIfNull bool              `protobuf:"varint,10,opt,name=option_error_if_null,json=optionErrorIfNull,proto3" json:"option_error_if_null,omitempty"`
	OptionErrorIfZero bool              `protobuf:"varint,11,opt,name=option_error_if_zero,json=optionErrorIfZero,proto3" json:"option_error_if_zero,omitempty"`
}

func (m *ExtendedRequest) Reset()                    { *m = ExtendedRequest{} }
func (*ExtendedRequest) ProtoMessage()               {}
func (*ExtendedRequest) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{1} }

func (m *ExtendedRequest) GetRequestMetadata() map[string]string {
	if m != nil {
		return m.RequestMetadata
	}
	return nil
}

func (m *ExtendedRequest) GetOptionErrorIfNull() bool {
	if m != nil {
		return m.OptionErrorIfNull
	}
	return false
}

func (m *ExtendedRequest) GetOptionErrorIfZero() bool {
	if m != nil {
		return m.OptionErrorIfZero
	}
	return false
}

type ExtendedResponse struct {
	Error *Error `protobuf:"bytes,10,opt,name=error" json:"error,omitempty"`
}

func (m *ExtendedResponse) Reset()                    { *m = ExtendedResponse{} }
func (*ExtendedResponse) ProtoMessage()               {}
func (*ExtendedResponse) Descriptor() ([]byte, []int) { return fileDescriptorInternal, []int{2} }

func (m *ExtendedResponse) GetError() *Error {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "internal.Error")
	proto.RegisterType((*ExtendedRequest)(nil), "internal.ExtendedRequest")
	proto.RegisterType((*ExtendedResponse)(nil), "internal.ExtendedResponse")
	proto.RegisterEnum("internal.ErrorType", ErrorType_name, ErrorType_value)
}
func (m *Error) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Error) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.Cause) > 0 {
		dAtA[i] = 0xa
		i++
		i = encodeVarintInternal(dAtA, i, uint64(len(m.Cause)))
		i += copy(dAtA[i:], m.Cause)
	}
	if m.Type != 0 {
		dAtA[i] = 0x10
		i++
		i = encodeVarintInternal(dAtA, i, uint64(m.Type))
	}
	return i, nil
}

func (m *ExtendedRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExtendedRequest) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if len(m.RequestMetadata) > 0 {
		for k, _ := range m.RequestMetadata {
			dAtA[i] = 0xa
			i++
			v := m.RequestMetadata[k]
			mapSize := 1 + len(k) + sovInternal(uint64(len(k))) + 1 + len(v) + sovInternal(uint64(len(v)))
			i = encodeVarintInternal(dAtA, i, uint64(mapSize))
			dAtA[i] = 0xa
			i++
			i = encodeVarintInternal(dAtA, i, uint64(len(k)))
			i += copy(dAtA[i:], k)
			dAtA[i] = 0x12
			i++
			i = encodeVarintInternal(dAtA, i, uint64(len(v)))
			i += copy(dAtA[i:], v)
		}
	}
	if m.OptionErrorIfNull {
		dAtA[i] = 0x50
		i++
		if m.OptionErrorIfNull {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	if m.OptionErrorIfZero {
		dAtA[i] = 0x58
		i++
		if m.OptionErrorIfZero {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i++
	}
	return i, nil
}

func (m *ExtendedResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalTo(dAtA)
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ExtendedResponse) MarshalTo(dAtA []byte) (int, error) {
	var i int
	_ = i
	var l int
	_ = l
	if m.Error != nil {
		dAtA[i] = 0x52
		i++
		i = encodeVarintInternal(dAtA, i, uint64(m.Error.Size()))
		n1, err := m.Error.MarshalTo(dAtA[i:])
		if err != nil {
			return 0, err
		}
		i += n1
	}
	return i, nil
}

func encodeFixed64Internal(dAtA []byte, offset int, v uint64) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	dAtA[offset+4] = uint8(v >> 32)
	dAtA[offset+5] = uint8(v >> 40)
	dAtA[offset+6] = uint8(v >> 48)
	dAtA[offset+7] = uint8(v >> 56)
	return offset + 8
}
func encodeFixed32Internal(dAtA []byte, offset int, v uint32) int {
	dAtA[offset] = uint8(v)
	dAtA[offset+1] = uint8(v >> 8)
	dAtA[offset+2] = uint8(v >> 16)
	dAtA[offset+3] = uint8(v >> 24)
	return offset + 4
}
func encodeVarintInternal(dAtA []byte, offset int, v uint64) int {
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return offset + 1
}
func (m *Error) Size() (n int) {
	var l int
	_ = l
	l = len(m.Cause)
	if l > 0 {
		n += 1 + l + sovInternal(uint64(l))
	}
	if m.Type != 0 {
		n += 1 + sovInternal(uint64(m.Type))
	}
	return n
}

func (m *ExtendedRequest) Size() (n int) {
	var l int
	_ = l
	if len(m.RequestMetadata) > 0 {
		for k, v := range m.RequestMetadata {
			_ = k
			_ = v
			mapEntrySize := 1 + len(k) + sovInternal(uint64(len(k))) + 1 + len(v) + sovInternal(uint64(len(v)))
			n += mapEntrySize + 1 + sovInternal(uint64(mapEntrySize))
		}
	}
	if m.OptionErrorIfNull {
		n += 2
	}
	if m.OptionErrorIfZero {
		n += 2
	}
	return n
}

func (m *ExtendedResponse) Size() (n int) {
	var l int
	_ = l
	if m.Error != nil {
		l = m.Error.Size()
		n += 1 + l + sovInternal(uint64(l))
	}
	return n
}

func sovInternal(x uint64) (n int) {
	for {
		n++
		x >>= 7
		if x == 0 {
			break
		}
	}
	return n
}
func sozInternal(x uint64) (n int) {
	return sovInternal(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (this *Error) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&Error{`,
		`Cause:` + fmt.Sprintf("%v", this.Cause) + `,`,
		`Type:` + fmt.Sprintf("%v", this.Type) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ExtendedRequest) String() string {
	if this == nil {
		return "nil"
	}
	keysForRequestMetadata := make([]string, 0, len(this.RequestMetadata))
	for k, _ := range this.RequestMetadata {
		keysForRequestMetadata = append(keysForRequestMetadata, k)
	}
	github_com_vaniila_protobuf_sortkeys.Strings(keysForRequestMetadata)
	mapStringForRequestMetadata := "map[string]string{"
	for _, k := range keysForRequestMetadata {
		mapStringForRequestMetadata += fmt.Sprintf("%v: %v,", k, this.RequestMetadata[k])
	}
	mapStringForRequestMetadata += "}"
	s := strings.Join([]string{`&ExtendedRequest{`,
		`RequestMetadata:` + mapStringForRequestMetadata + `,`,
		`OptionErrorIfNull:` + fmt.Sprintf("%v", this.OptionErrorIfNull) + `,`,
		`OptionErrorIfZero:` + fmt.Sprintf("%v", this.OptionErrorIfZero) + `,`,
		`}`,
	}, "")
	return s
}
func (this *ExtendedResponse) String() string {
	if this == nil {
		return "nil"
	}
	s := strings.Join([]string{`&ExtendedResponse{`,
		`Error:` + strings.Replace(fmt.Sprintf("%v", this.Error), "Error", "Error", 1) + `,`,
		`}`,
	}, "")
	return s
}
func valueToStringInternal(v interface{}) string {
	rv := reflect.ValueOf(v)
	if rv.IsNil() {
		return "nil"
	}
	pv := reflect.Indirect(rv).Interface()
	return fmt.Sprintf("*%v", pv)
}
func (m *Error) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Error: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Error: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Cause", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= (uint64(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthInternal
			}
			postIndex := iNdEx + intStringLen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Cause = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Type", wireType)
			}
			m.Type = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Type |= (ErrorType(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExtendedRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExtendedRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExtendedRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RequestMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.RequestMetadata == nil {
				m.RequestMetadata = make(map[string]string)
			}
			var mapkey string
			var mapvalue string
			for iNdEx < postIndex {
				entryPreIndex := iNdEx
				var wire uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowInternal
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					wire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				fieldNum := int32(wire >> 3)
				if fieldNum == 1 {
					var stringLenmapkey uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInternal
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapkey |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapkey := int(stringLenmapkey)
					if intStringLenmapkey < 0 {
						return ErrInvalidLengthInternal
					}
					postStringIndexmapkey := iNdEx + intStringLenmapkey
					if postStringIndexmapkey > l {
						return io.ErrUnexpectedEOF
					}
					mapkey = string(dAtA[iNdEx:postStringIndexmapkey])
					iNdEx = postStringIndexmapkey
				} else if fieldNum == 2 {
					var stringLenmapvalue uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowInternal
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						stringLenmapvalue |= (uint64(b) & 0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					intStringLenmapvalue := int(stringLenmapvalue)
					if intStringLenmapvalue < 0 {
						return ErrInvalidLengthInternal
					}
					postStringIndexmapvalue := iNdEx + intStringLenmapvalue
					if postStringIndexmapvalue > l {
						return io.ErrUnexpectedEOF
					}
					mapvalue = string(dAtA[iNdEx:postStringIndexmapvalue])
					iNdEx = postStringIndexmapvalue
				} else {
					iNdEx = entryPreIndex
					skippy, err := skipInternal(dAtA[iNdEx:])
					if err != nil {
						return err
					}
					if skippy < 0 {
						return ErrInvalidLengthInternal
					}
					if (iNdEx + skippy) > postIndex {
						return io.ErrUnexpectedEOF
					}
					iNdEx += skippy
				}
			}
			m.RequestMetadata[mapkey] = mapvalue
			iNdEx = postIndex
		case 10:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionErrorIfNull", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OptionErrorIfNull = bool(v != 0)
		case 11:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field OptionErrorIfZero", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.OptionErrorIfZero = bool(v != 0)
		default:
			iNdEx = preIndex
			skippy, err := skipInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ExtendedResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowInternal
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ExtendedResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ExtendedResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Error", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthInternal
			}
			postIndex := iNdEx + msglen
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Error == nil {
				m.Error = &Error{}
			}
			if err := m.Error.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipInternal(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if skippy < 0 {
				return ErrInvalidLengthInternal
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipInternal(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowInternal
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
			return iNdEx, nil
		case 1:
			iNdEx += 8
			return iNdEx, nil
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowInternal
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			iNdEx += length
			if length < 0 {
				return 0, ErrInvalidLengthInternal
			}
			return iNdEx, nil
		case 3:
			for {
				var innerWire uint64
				var start int = iNdEx
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return 0, ErrIntOverflowInternal
					}
					if iNdEx >= l {
						return 0, io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					innerWire |= (uint64(b) & 0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				innerWireType := int(innerWire & 0x7)
				if innerWireType == 4 {
					break
				}
				next, err := skipInternal(dAtA[start:])
				if err != nil {
					return 0, err
				}
				iNdEx = start + next
			}
			return iNdEx, nil
		case 4:
			return iNdEx, nil
		case 5:
			iNdEx += 4
			return iNdEx, nil
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
	}
	panic("unreachable")
}

var (
	ErrInvalidLengthInternal = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowInternal   = fmt.Errorf("proto: integer overflow")
)

func init() { proto.RegisterFile("internal.proto", fileDescriptorInternal) }

var fileDescriptorInternal = []byte{
	// 418 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x92, 0xb1, 0x6f, 0xd3, 0x40,
	0x14, 0xc6, 0x73, 0x69, 0x53, 0x9a, 0x17, 0xa9, 0x31, 0x47, 0x84, 0x2c, 0x0f, 0x27, 0x2b, 0x02,
	0x11, 0x31, 0xd8, 0x28, 0x2c, 0xc0, 0x58, 0x14, 0x24, 0x06, 0x18, 0x0c, 0x0c, 0xc0, 0x60, 0x5d,
	0x9a, 0x97, 0x60, 0xf5, 0x72, 0x67, 0xce, 0xe7, 0x82, 0x99, 0x18, 0x51, 0x27, 0xc4, 0xde, 0x89,
	0x7f, 0x82, 0x91, 0xb1, 0x23, 0x23, 0x23, 0x35, 0xff, 0x08, 0xf2, 0x9d, 0x5b, 0x28, 0xca, 0xe4,
	0xf7, 0x7b, 0xef, 0x7d, 0xbe, 0xef, 0x3e, 0x1d, 0xec, 0x65, 0xd2, 0xa0, 0x96, 0x5c, 0x44, 0xb9,
	0x56, 0x46, 0xd1, 0xdd, 0x73, 0x0e, 0xee, 0xac, 0x32, 0xf3, 0xa6, 0x9c, 0x47, 0x07, 0x6a, 0x1d,
	0x1f, 0x71, 0x99, 0x65, 0x82, 0xc7, 0x76, 0x67, 0x5e, 0x2e, 0xe3, 0x95, 0x5a, 0x29, 0x0b, 0xb6,
	0x72, 0xda, 0xf1, 0x23, 0xe8, 0xcd, 0xb4, 0x56, 0x9a, 0x8e, 0xa0, 0x77, 0xc0, 0xcb, 0x02, 0x7d,
	0x12, 0x92, 0x49, 0x3f, 0x71, 0x40, 0x6f, 0xc1, 0xb6, 0xa9, 0x72, 0xf4, 0xbb, 0x21, 0x99, 0xec,
	0x4d, 0xaf, 0x45, 0x17, 0x27, 0x5b, 0xd1, 0xf3, 0x2a, 0xc7, 0xc4, 0x2e, 0x8c, 0xbf, 0x74, 0x61,
	0x38, 0x7b, 0x6f, 0x50, 0x2e, 0x70, 0x91, 0xe0, 0xdb, 0x12, 0x0b, 0x43, 0x5f, 0x82, 0xa7, 0x5d,
	0x99, 0xae, 0xd1, 0xf0, 0x05, 0x37, 0xdc, 0x27, 0xe1, 0xd6, 0x64, 0x30, 0x8d, 0xfe, 0xf9, 0xd1,
	0x65, 0x51, 0xd4, 0x7e, 0x9f, 0xb4, 0x82, 0x99, 0x34, 0xba, 0x4a, 0x86, 0xfa, 0x72, 0x97, 0xc6,
	0x30, 0x52, 0xb9, 0xc9, 0x94, 0x4c, 0xb1, 0x31, 0x92, 0x66, 0xcb, 0x54, 0x96, 0x42, 0xf8, 0x10,
	0x92, 0xc9, 0x6e, 0x72, 0xd5, 0xcd, 0xac, 0xc7, 0xc7, 0xcb, 0xa7, 0xa5, 0x10, 0x9b, 0x04, 0x1f,
	0x50, 0x2b, 0x7f, 0xb0, 0x41, 0xf0, 0x0a, 0xb5, 0x0a, 0xf6, 0x61, 0xb4, 0xc9, 0x0a, 0xf5, 0x60,
	0xeb, 0x10, 0xab, 0x36, 0xa5, 0xa6, 0x6c, 0x92, 0x3b, 0xe2, 0xa2, 0x74, 0x21, 0xf5, 0x13, 0x07,
	0x0f, 0xba, 0xf7, 0xc8, 0xf8, 0x3e, 0x78, 0x7f, 0xaf, 0x57, 0xe4, 0x4a, 0x16, 0x48, 0x6f, 0x42,
	0xcf, 0x3a, 0xb0, 0x56, 0x07, 0xd3, 0xe1, 0x7f, 0x91, 0x26, 0x6e, 0x7a, 0xfb, 0x35, 0xf4, 0x2f,
	0x22, 0xa6, 0x3e, 0x5c, 0x79, 0x21, 0x0f, 0xa5, 0x7a, 0x27, 0xbd, 0x4e, 0x30, 0x38, 0x3e, 0x09,
	0xcf, 0x91, 0x5e, 0x87, 0x9d, 0x67, 0x55, 0x61, 0x70, 0xed, 0x91, 0x00, 0x8e, 0x4f, 0xc2, 0x96,
	0x9a, 0xfe, 0x43, 0x91, 0xa1, 0x34, 0x5e, 0xd7, 0xf5, 0x1d, 0x05, 0xdb, 0x9f, 0xbe, 0xb2, 0xce,
	0xfe, 0x8d, 0xd3, 0x33, 0x46, 0x7e, 0x9e, 0xb1, 0xce, 0xc7, 0x9a, 0x91, 0x6f, 0x35, 0x23, 0xdf,
	0x6b, 0x46, 0x4e, 0x6b, 0x46, 0x7e, 0xd4, 0x8c, 0xfc, 0xaa, 0x19, 0xf9, 0xfc, 0x9b, 0x75, 0xe6,
	0x3b, 0xf6, 0x85, 0xdc, 0xfd, 0x13, 0x00, 0x00, 0xff, 0xff, 0x58, 0xfb, 0x0f, 0x11, 0x6f, 0x02,
	0x00, 0x00,
}
